import {COUNTRIES,POSITIONS,BUILDS,SKILLS,ATTRIBUTE_INFO,DATA_SOURCES} from './data.js';
import {MatchEngine} from './engine.js';
import {createCareer,loadCareer,saveCareer,clearCareer,clubById,countryById,buildById,nextFixture,sortedTable,leaguePosition,lineup11,clubStrength,completeCareerMatch,trainAttribute,unlockSkill,toggleSkill,setInstruction,startNextSeason,asyncOpponent,asyncLineup,recordAsyncResult} from './career.js';

const app=document.querySelector('#app');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let state=loadCareer(),view='home',live=null,raf=null,lastTs=0;
let setup={step:1,playerName:'',nationality:'AR',position:'CM',build:'creator',countryId:'AR',clubId:null};

function save(){if(state)saveCareer(state);}
function stop(){if(raf)cancelAnimationFrame(raf);raf=null;lastTs=0;}
function toast(text){$('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=text;document.body.appendChild(e);setTimeout(()=>e.remove(),2200);}
function captureSetup(){const n=$('#playerName');if(n)setup.playerName=n.value;const nat=$('#nationality');if(nat)setup.nationality=nat.value;const pos=$('#position');if(pos)setup.position=pos.value;}
function render(){stop();if(!state)return renderSetup();app.innerHTML=`<div class="shell">${top()}<div class="layout">${nav()}<main class="main">${content()}</main></div></div>`;bind();if(view==='match'&&live)mountMatch();}

function top(){const c=clubById(state.clubId);return `<header class="top"><button class="logo" data-view="home"><b>CAREER ELEVEN</b><small>2D · 11v11 AUTOPLAY</small></button><div class="head"><i style="background:${c.color}"></i><strong>${esc(state.player.name)}</strong><span>${esc(c.name)}</span><span>${state.player.position} · OVR ${state.player.rating}</span><b>LV ${state.progress.level}</b></div></header>`;}
function nav(){const items=[['home','⌂','Carrera'],['player','●','Mi jugador'],['build','◆','Build'],['training','↗','Entrenar'],['match','▶','Partido'],['league','▦','Liga'],['async','◎','PvP Async'],['sources','i','Fuentes']];return `<nav class="nav">${items.map(([id,ico,label])=>`<button class="nav-btn ${view===id?'on':''}" data-view="${id}"><span>${ico}</span>${label}</button>`).join('')}<button class="nav-btn reset" id="reset"><span>↺</span>Nueva carrera</button></nav>`;}
function content(){return({home:homeView,player:playerView,build:buildView,training:trainingView,match:matchView,league:leagueView,async:asyncView,sources:sourcesView}[view]||homeView)();}
function hero(k,h,p='',actions=''){return `<div class="hero"><div><div class="eyebrow">${k}</div><h1>${h}</h1>${p?`<p>${p}</p>`:''}</div>${actions?`<div class="actions">${actions}</div>`:''}</div>`;}

function renderSetup(){let body='';if(setup.step===1){body=`<div class="setup-row"><label>Nombre de tu jugador<input id="playerName" maxlength="24" value="${esc(setup.playerName)}" placeholder="Nombre de tu jugador" autocomplete="off"></label><label>Nacionalidad<select id="nationality">${COUNTRIES.map(c=>`<option value="${c.id}" ${setup.nationality===c.id?'selected':''}>${c.flag} ${c.name}</option>`).join('')}</select></label><label>Posición<select id="position">${POSITIONS.map(p=>`<option value="${p.id}" ${setup.position===p.id?'selected':''}>${p.name}</option>`).join('')}</select></label></div><h3>Build inicial</h3><div class="grid builds">${BUILDS.map(b=>`<button class="choice ${setup.build===b.id?'selected':''}" data-build="${b.id}"><b>${esc(b.name)}</b><span>${esc(b.desc)}</span></button>`).join('')}</div><button class="btn next" data-next>Elegir liga</button>`;}else if(setup.step===2){body=`<div class="grid countries">${COUNTRIES.map(c=>`<button class="choice ${setup.countryId===c.id?'selected':''}" data-country="${c.id}"><big>${c.flag}</big><b>${c.name}</b><span>${c.league} · ${c.clubs.length} clubes</span></button>`).join('')}</div><div class="actions bottom"><button class="btn ghost" data-back>Atrás</button><button class="btn" data-next>Elegir club</button></div>`;}else{const co=countryById(setup.countryId);body=`<div class="grid clubs">${co.clubs.map(c=>`<button class="choice club ${setup.clubId===c.id?'selected':''}" data-club="${c.id}"><i style="background:${c.color}"></i><b>${esc(c.name)}</b><span>Rep ${c.reputation}</span></button>`).join('')}</div><div class="actions bottom"><button class="btn ghost" data-back>Atrás</button><button class="btn" id="start" ${!setup.clubId?'disabled':''}>Empezar carrera</button></div>`;}
  app.innerHTML=`<section class="setup"><div class="setup-card"><div class="eyebrow">MODO CARRERA · 11 CONTRA 11</div><h1>Tu jugador.<br><span>Tu carrera.</span></h1><p>Autoplay 2D con 22 jugadores. Conducción por toques, movimiento por espacios y atributos que cambian lo que pasa en cancha.</p><div class="steps">${[1,2,3].map(n=>`<i class="${setup.step>=n?'on':''}"></i>`).join('')}</div>${body}<small>El nombre empieza vacío y se conserva al cambiar build, posición o pantalla.</small></div></section>`;bindSetup();}
function bindSetup(){const input=$('#playerName');if(input)input.addEventListener('input',e=>{setup.playerName=e.target.value;});const nat=$('#nationality');if(nat)nat.addEventListener('change',e=>{setup.nationality=e.target.value;});const pos=$('#position');if(pos)pos.addEventListener('change',e=>{setup.position=e.target.value;});$('[data-next]')?.addEventListener('click',()=>{captureSetup();if(setup.step===1&&!(setup.playerName||'').trim()){toast('Escribí el nombre de tu jugador.');return;}setup.step++;renderSetup();});$('[data-back]')?.addEventListener('click',()=>{captureSetup();setup.step--;renderSetup();});$$('[data-build]').forEach(b=>b.onclick=()=>{captureSetup();setup.build=b.dataset.build;renderSetup();});$$('[data-country]').forEach(b=>b.onclick=()=>{setup.countryId=b.dataset.country;setup.clubId=null;renderSetup();});$$('[data-club]').forEach(b=>b.onclick=()=>{setup.clubId=b.dataset.club;renderSetup();});$('#start')?.addEventListener('click',()=>{captureSetup();if(!(setup.playerName||'').trim()){setup.step=1;renderSetup();toast('El nombre es obligatorio.');return;}state=createCareer(setup);save();view='home';render();});}

function homeView(){const f=nextFixture(state),club=clubById(state.clubId),s=state.seasonStats,b=buildById(state.player.build);return `${hero(`${countryById(state.countryId).league} · Temporada ${state.season}`,`${esc(state.player.name)} <span>${state.player.position}</span>`,`Build ${b.name} · ${esc(club.name)}`,`<button class="btn ghost" data-view="training">Entrenar</button><button class="btn" data-view="match">Ir al partido</button>`)}<section class="grid metrics">${metric('OVR',state.player.rating)}${metric('Nivel',state.progress.level)}${metric('XP',`${state.progress.xp}/${state.progress.nextXp}`)}${metric('Posición liga','#'+leaguePosition(state))}${metric('Rating temp.',s.apps?s.avgRating.toFixed(2):'—')}</section><section class="grid two"><div class="card"><div class="section"><div><div class="eyebrow">PRÓXIMO PARTIDO</div><h2>${f?fixtureName(f):'Temporada terminada'}</h2></div>${f?`<span class="pill">J${f.week}</span>`:''}</div>${f?`<div class="versus"><div><b>${esc(club.name)}</b><span>${Math.round(clubStrength(state,state.clubId))}</span></div><strong>VS</strong><div><b>${esc(clubById(f.home===state.clubId?f.away:f.home).name)}</b><span>${Math.round(clubStrength(state,f.home===state.clubId?f.away:f.home))}</span></div></div><button class="btn wide" data-view="match">Jugar 11v11</button>`:`<p>Terminaste #${leaguePosition(state)}. Podés empezar la siguiente temporada.</p><button class="btn" id="nextSeason">Nueva temporada</button>`}</div><div class="card player-focus"><div class="section"><div><div class="eyebrow">TU TEMPORADA</div><h2>${s.goals} G · ${s.assists} A</h2></div><span class="rating-big">${state.player.rating}</span></div><div class="mini-stats"><span>Partidos <b>${s.apps}</b></span><span>Regates <b>${s.dribblePct.toFixed(0)}%</b></span><span>Pases <b>${s.passPct.toFixed(0)}%</b></span><span>MOTM <b>${s.motm}</b></span></div><div class="xpbar"><i style="width:${Math.min(100,state.progress.xp/state.progress.nextXp*100)}%"></i></div><small>${state.progress.skillPoints} punto(s) de habilidad · ${state.progress.fans.toLocaleString()} fans</small></div></section><section class="card"><div class="section"><h3>Tabla</h3><button class="text" data-view="league">Ver liga</button></div>${table()}</section>`;}
const metric=(a,b)=>`<div class="card metric"><span>${a}</span><b>${b}</b></div>`;
function fixtureName(f){return `${clubById(f.home).name} vs ${clubById(f.away).name}`;}

function playerView(){const p=state.player;return `${hero('PERFIL','Mi jugador',`${p.age} años · ${p.position} · ${p.country}`)}<section class="grid two"><div class="card player-card"><div class="player-card-top"><div><span class="pill">${buildById(p.build).name}</span><h2>${esc(p.name)}</h2><p>${esc(clubById(state.clubId).name)}</p></div><span class="overall">${p.rating}</span></div><div class="attrs">${attributeRows(p)}</div></div><div class="card"><h3>Qué significa cada stat dentro del partido</h3>${Object.entries(ATTRIBUTE_INFO).map(([k,v])=>`<div class="meaning"><b>${labelAttr(k)}</b><span>${esc(v)}</span></div>`).join('')}</div></section>`;}
function attributeRows(p){return ['pace','shooting','passing','dribbling','defense','physical','ballControl','vision','stamina','composure'].map(k=>`<div><span>${labelAttr(k)}</span><div class="bar"><i style="width:${p[k]}%"></i></div><b>${p[k]}</b></div>`).join('');}
function labelAttr(k){return({pace:'PAC',shooting:'SHO',passing:'PAS',dribbling:'DRI',defense:'DEF',physical:'PHY',ballControl:'CTRL',vision:'VIS',stamina:'STA',composure:'COMP'})[k]||k.toUpperCase();}

function buildView(){const p=state.player;return `${hero('ARQUETIPO Y HABILIDADES','Build',`Build base: ${buildById(p.build).name} · máximo 3 habilidades equipadas.`)}<section class="grid two"><div class="card"><div class="section"><h3>Habilidades</h3><span class="pill">${state.progress.skillPoints} puntos</span></div><div class="skills">${SKILLS.map(s=>{const unlocked=p.unlockedSkills.includes(s.id),equipped=p.skills.includes(s.id);return `<button class="skill ${equipped?'equipped':''} ${unlocked?'unlocked':''}" data-skill="${s.id}"><b>${esc(s.name)}</b><span>${esc(s.desc)}</span><em>${equipped?'EQUIPADA':unlocked?'DESBLOQUEADA':'1 PUNTO'}</em></button>`;}).join('')}</div></div><div class="card"><h3>Tendencias de tu IA</h3><p>Tu jugador sigue siendo autoplay, pero estas preferencias cambian sus decisiones con pelota.</p>${instruction('shoot','Buscar remate',p.instructions.shoot)}${instruction('dribble','Buscar 1v1',p.instructions.dribble)}${instruction('risk','Riesgo de pase',p.instructions.risk)}<div class="equipped"><b>Equipadas</b>${p.skills.map(id=>`<span>${esc(SKILLS.find(s=>s.id===id)?.name||id)}</span>`).join('')}</div></div></section>`;}
function instruction(k,n,v){return `<label class="range">${n}<b id="out-${k}">${v}</b><input data-instruction="${k}" type="range" min="0" max="100" value="${v}"></label>`;}

function trainingView(){const p=state.player,attrs=['pace','shooting','passing','dribbling','defense','physical','ballControl','vision','stamina','composure'];return `${hero('DESARROLLO SEMANAL','Entrenamiento',`${state.progress.trainingPoints} sesiones disponibles. Lo que subís acá cambia directamente el motor 11v11.`)}<section class="grid training">${attrs.map(k=>`<button class="card train-card" data-train="${k}" ${state.progress.trainingPoints<=0||p[k]>=99?'disabled':''}><span>${labelAttr(k)}</span><b>${p[k]}</b><small>${esc(ATTRIBUTE_INFO[k])}</small><em>+${p[k]<70?2:1}</em></button>`).join('')}</section>`;}

function matchView(){if(live)return liveView();const f=nextFixture(state);if(!f)return `${hero('MATCHDAY','Sin partido de liga pendiente','La temporada terminó.')}<section class="card"><button class="btn" data-view="home">Volver</button></section>`;const opp=f.home===state.clubId?f.away:f.home,xi=lineup11(state,state.clubId),me=xi.find(p=>p.isUser);return `${hero(`JORNADA ${f.week}`,'Partido 11v11',fixtureName(f))}<section class="grid two"><div class="card"><h3>Tu lugar en el XI</h3><div class="xi">${xi.map(p=>`<div class="${p.isUser?'user':''}"><b>${esc(p.name)}</b><span>${p.engineRole} · ${p.rating}</span></div>`).join('')}</div>${me?`<p class="position-note">Tu posición elegida: <b>${state.player.position}</b>. Rol de cancha: <b>${me.engineRole}</b>.</p>`:''}</div><div class="card"><h3>Seguimiento individual</h3><p>La cámara sigue a <b>${esc(state.player.name)}</b>. El aro verde y la flecha marcan tu jugador. El rating cambia con cada pase, regate, remate, robo, pérdida, gol o asistencia.</p><div class="plan"><span>Tu club <b>${Math.round(clubStrength(state,state.clubId))}</b></span><span>Rival <b>${Math.round(clubStrength(state,opp))}</b></span><span>Cámara <b>${state.settings.camera}</b></span></div></div></section><button class="btn kickoff" id="kickoff">▶ JUGAR PARTIDO 11v11</button>`;}

function liveView(){const r=live.engine.report(),u=r.userPerformance||{};return `${hero(live.mode==='async'?'PVP ASYNC · GHOST':'PARTIDO EN VIVO',`${esc(live.engine.names[0])} <span id="score">${r.score[0]} - ${r.score[1]}</span> ${esc(live.engine.names[1])}`,`<span id="minute">${Math.round(live.engine.minute)}'</span>`)}<section class="live-layout"><div class="card canvas-card"><canvas id="canvas" width="1100" height="700"></canvas><div class="match-controls"><div>${[1,2,4,8].map(n=>`<button class="speed ${state.settings.speed===n?'on':''}" data-speed="${n}">x${n}</button>`).join('')}<button class="speed ${state.settings.camera==='player'?'on':''}" id="camera">Cámara jugador</button></div>${live.engine.finished?'<button class="btn" id="commit">Guardar resultado</button>':'<button class="btn ghost" id="abort">Salir sin guardar</button>'}</div></div><aside class="card hud"><div class="live-rating"><span>RATING</span><b id="rating">${Number(u.rating||6).toFixed(1)}</b></div><div id="playerStats">${playerStats(u)}</div><h3>Partido</h3><div id="teamStats">${teamStats(r)}</div><h3>Relato</h3><div class="events" id="events">${events(r)}</div></aside></section>`;}
function playerStats(u){return `<div class="player-live"><span>Toques <b>${u.touches||0}</b></span><span>Pases <b>${u.passesCompleted||0}/${u.passesAttempted||0}</b></span><span>Regates <b>${u.dribblesCompleted||0}/${u.dribblesAttempted||0}</b></span><span>Tiros <b>${u.shots||0}</b></span><span>Goles <b>${u.goals||0}</b></span><span>Asist. <b>${u.assists||0}</b></span><span>Robos <b>${u.tackles||0}</b></span><span>Intercep. <b>${u.interceptions||0}</b></span><span>Pérdidas <b>${u.turnovers||0}</b></span></div>`;}
function teamStats(r){const p=r.possession||[50,50];return `<div class="team-live"><div><b>${p[0]}%</b><span>Posesión</span><b>${p[1]}%</b></div><div><b>${r.stats.shots[0]}</b><span>Tiros</span><b>${r.stats.shots[1]}</b></div><div><b>${r.stats.passes[0]}</b><span>Pases</span><b>${r.stats.passes[1]}</b></div><div><b>${r.stats.dribbles[0]}</b><span>Regates</span><b>${r.stats.dribbles[1]}</b></div></div>`;}
function events(r){return (r.events||[]).slice(0,20).map(e=>`<p><b>${e.minute}'</b> ${esc(e.text)}</p>`).join('')||'<p>Empieza el partido.</p>';}

function leagueView(){return `${hero(countryById(state.countryId).league,'Liga',`${countryById(state.countryId).clubs.length} clubes · ida y vuelta`)}<section class="card">${table()}</section>`;}
function table(){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Club</th><th>P</th><th>DG</th><th>Pts</th></tr></thead><tbody>${sortedTable(state).map((r,i)=>`<tr class="${r.clubId===state.clubId?'me':''}"><td>${i+1}</td><td>${esc(clubById(r.clubId).name)}</td><td>${r.p}</td><td>${r.gf-r.ga}</td><td><b>${r.pts}</b></td></tr>`).join('')}</tbody></table></div>`;}

function asyncView(){const opp=asyncOpponent(state);return `${hero('LIGA GHOST','PvP asíncrono','Versión local: perfiles ghost entran realmente al XI rival. La capa de cuentas/backend viene después.')}<section class="grid two"><div class="card"><h3>Tu ranking</h3><div class="rank">${state.asyncLeague.rating}</div><p>${state.asyncLeague.division} · ${state.asyncLeague.record.w}V ${state.asyncLeague.record.d}E ${state.asyncLeague.record.l}D</p></div><div class="card"><h3>Próximo ghost</h3>${opp?`<h2>${esc(opp.name)}</h2><p>${opp.position} · ${opp.rating} OVR · ${esc(opp.build)}</p><button class="btn wide" id="asyncPlay">Jugar ghost 11v11</button>`:'<p>Sin rivales disponibles.</p>'}</div></section>`;}
function sourcesView(){return `${hero('DATOS','Fuentes','Los planteles completos usan datos abiertos cuando existen. Los ratings generados se identifican como valores de juego.') }<section class="card sources">${DATA_SOURCES.map(s=>`<div><b>${esc(s.name)}</b><span>${esc(s.repo)} · ${esc(s.license)}</span><p>${esc(s.usage)}</p></div>`).join('')}</section>`;}

function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});$('#reset')?.addEventListener('click',()=>{if(confirm('¿Borrar esta carrera?')){clearCareer();state=null;live=null;setup={step:1,playerName:'',nationality:'AR',position:'CM',build:'creator',countryId:'AR',clubId:null};render();}});$('#nextSeason')?.addEventListener('click',()=>{const r=startNextSeason(state);save();toast(r.message||'Nueva temporada');render();});$$('[data-train]').forEach(b=>b.onclick=()=>{const r=trainAttribute(state,b.dataset.train);save();toast(r.message);render();});$$('[data-skill]').forEach(b=>b.onclick=()=>{const id=b.dataset.skill;const unlocked=state.player.unlockedSkills.includes(id);const r=unlocked?toggleSkill(state,id):unlockSkill(state,id);save();toast(r.message);render();});$$('[data-instruction]').forEach(i=>i.oninput=e=>{const v=+e.target.value;setInstruction(state,e.target.dataset.instruction,v);$(`#out-${e.target.dataset.instruction}`).textContent=v;save();});$('#kickoff')?.addEventListener('click',startLeagueMatch);$('#asyncPlay')?.addEventListener('click',startAsyncMatch);}
function startLeagueMatch(){const f=nextFixture(state);if(!f)return;const home=lineup11(state,f.home),away=lineup11(state,f.away);live={mode:'league',fixtureId:f.id,engine:new MatchEngine(home,away,{homeName:clubById(f.home).name,awayName:clubById(f.away).name,homeColor:clubById(f.home).color,awayColor:clubById(f.away).color,homeTactics:state.world[f.home].tactics,awayTactics:state.world[f.away].tactics,userId:'user-player',seed:`league-${state.season}-${f.id}-${state.player.name}`})};render();}
function startAsyncMatch(){const opp=asyncOpponent(state);if(!opp)return;const home=lineup11(state,state.clubId,{forceUser:true}),away=asyncLineup(state,opp);live={mode:'async',opponent:opp,engine:new MatchEngine(home,away,{homeName:clubById(state.clubId).name,awayName:`Ghost XI`,homeColor:clubById(state.clubId).color,awayColor:'#7c5cff',homeTactics:state.world[state.clubId].tactics,awayTactics:{formation:'4-3-3',pressing:60,tempo:58,width:55,directness:55},userId:'user-player',ghostId:opp.instanceId,seed:`ghost-${state.season}-${opp.id}-${state.player.name}`})};render();}
function mountMatch(){const canvas=$('#canvas');if(!canvas)return;const ctx=canvas.getContext('2d');const draw=()=>live.engine.draw(ctx,canvas.width,canvas.height,{camera:state.settings.camera});draw();$$('[data-speed]').forEach(b=>b.onclick=()=>{state.settings.speed=+b.dataset.speed;save();render();});$('#camera')?.addEventListener('click',()=>{state.settings.camera=state.settings.camera==='player'?'full':'player';save();render();});$('#abort')?.addEventListener('click',()=>{live=null;render();});$('#commit')?.addEventListener('click',commitLive);if(!live.engine.finished){lastTs=performance.now();raf=requestAnimationFrame(loop);}}
function loop(ts){if(!live||view!=='match')return;const canvas=$('#canvas');if(!canvas)return;const dt=Math.min(.034,(ts-lastTs)/1000||.016);lastTs=ts;for(let i=0;i<state.settings.speed&&!live.engine.finished;i++)live.engine.step(dt);live.engine.draw(canvas.getContext('2d'),canvas.width,canvas.height,{camera:state.settings.camera});const r=live.engine.report(),u=r.userPerformance||{};$('#score').textContent=`${r.score[0]} - ${r.score[1]}`;$('#minute').textContent=`${Math.round(live.engine.minute)}'`;$('#rating').textContent=Number(u.rating||6).toFixed(1);$('#playerStats').innerHTML=playerStats(u);$('#teamStats').innerHTML=teamStats(r);$('#events').innerHTML=events(r);if(live.engine.finished){raf=null;render();}else raf=requestAnimationFrame(loop);}
function commitLive(){const report=live.engine.report();let r;if(live.mode==='league')r=completeCareerMatch(state,live.fixtureId,report);else r=recordAsyncResult(state,live.opponent,report);save();live=null;toast(r.message||'Resultado guardado');view='home';render();}

render();
