import {buildsForPosition} from './argentina-data-v1.js';

const NAV_KEY='career-eleven-ui:nav-collapsed';
let collapsed=false,matchStartPending=false;
try{collapsed=localStorage.getItem(NAV_KEY)==='1';}catch{}

const CSS=`
:root{--bg:#071a2b!important;--panel:#0b2237!important;--panel2:#10304d!important;--line:#28577a!important;--text:#f7fbff!important;--muted:#9fc3da!important;--lime:#75aadb!important;--gold:#f6c453!important;--red:#e65b61!important;--violet:#8bb7ff!important;--shadow:0 22px 60px #00102088!important}
html,body{background:radial-gradient(circle at 18% 0,#17486b 0,#071a2b 34%,#04111e 100%)!important;font-family:"Bahnschrift Condensed","Arial Narrow","Roboto Condensed",Arial,sans-serif!important}body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.045;background:repeating-linear-gradient(90deg,#fff 0,#fff 7vw,transparent 7vw,transparent 14vw);z-index:-1}
.top{background:#061827f2!important;border-bottom-color:#2f668c!important}.logo b,.eyebrow,.text,.player-focus .rating-big,.overall,.live-rating b,.events b,.meaning b{color:#75aadb!important}.btn{background:#75aadb!important;color:#04111e!important}.btn.ghost{background:#102d46!important;color:#f7fbff!important}.nav-btn.on{box-shadow:inset 3px 0 #75aadb!important}.card,.setup-card{background:linear-gradient(180deg,#10304d,#0a2135)!important}.choice,.skill,.mini-stats span,.season-grid span,.xi>div,.plan span{background:#081d30!important}.bar i,.xpbar i,.training-live-progress i{background:#75aadb!important}.choice:hover,.choice.selected,.skill.equipped,.xi .user{border-color:#75aadb!important}.top:after{content:"ARG";font-weight:950;letter-spacing:.14em;color:#f6c453;font-size:10px;margin-left:8px}
.arg-nav-toggle{border:1px solid #28577a;background:#0b2237;color:#f7fbff;border-radius:8px;padding:7px 9px;font-weight:900;margin-right:8px}.top .logo{display:flex;align-items:center;gap:8px}.top .logo:before{content:"🇦🇷";font-size:18px}.layout{transition:grid-template-columns .18s ease}.nav{transition:width .18s ease,transform .18s ease}.nav-collapsed .layout{grid-template-columns:64px minmax(0,1fr)!important}.nav-collapsed .nav{padding-left:7px;padding-right:7px}.nav-collapsed .nav-btn{font-size:0;justify-content:center;padding:11px 8px}.nav-collapsed .nav-btn span{font-size:16px;width:auto}.nav-collapsed .main{min-width:0}
body.match-live-active .main{padding-top:10px}body.match-live-active .hero{position:sticky;top:62px;z-index:15;margin:0 0 8px;padding:8px 12px;background:#061827f3;border:1px solid #28577a;border-radius:12px;align-items:center}body.match-live-active .hero .eyebrow,body.match-live-active .hero p{display:none}body.match-live-active .hero h1{font-size:clamp(18px,2.4vw,28px);margin:0;display:flex;align-items:center;gap:12px;flex-wrap:wrap}body.match-live-active .hero h1 span{color:#f7fbff!important;background:#103b5d;border:1px solid #75aadb;border-radius:9px;padding:4px 10px}body.match-live-active .canvas-card{display:flex;flex-direction:column;align-items:stretch}body.match-live-active #canvas{display:block;width:auto!important;max-width:100%!important;height:auto!important;max-height:calc(100vh - 205px);margin:0 auto;aspect-ratio:11/7}body.match-live-active .live-layout{grid-template-columns:minmax(0,1fr) minmax(235px,280px)!important;gap:10px}body.match-live-active .hud{top:126px;max-height:calc(100vh - 140px);overflow:auto}.match-controls{width:100%}
.pc-shell{background:#071a2b!important}.pc-card,.pc-stage,.pc-offer,.pc-overall{background:#0b2237!important;border-color:#28577a!important}.pc-card button,.pc-btn{background:#75aadb!important;color:#04111e!important}.pc-head h1 span,.pc-overall b,.pc-progress .done,.pc-growth b,.pc-offer .interest{color:#75aadb!important}.pc-progress .done,.pc-card.done{border-color:#75aadb!important}.pc-stagebar i{background:#75aadb!important}[data-build-hidden="1"]{display:none!important}
@media(max-width:1100px){.layout{grid-template-columns:1fr!important}.nav{width:100%!important}.nav-collapsed .nav{display:none!important}.nav-collapsed .layout{grid-template-columns:1fr!important}body.match-live-active .live-layout{grid-template-columns:1fr!important}body.match-live-active .hud{position:static;max-height:none}body.match-live-active #canvas{max-height:calc(100vh - 225px)}}
@media(max-width:720px){.top{height:54px}.arg-nav-toggle{padding:6px 8px}body.match-live-active .main{padding:7px}body.match-live-active .hero{top:54px;margin:0 0 5px;padding:6px 8px}body.match-live-active .hero h1{font-size:17px;gap:7px}body.match-live-active #canvas{max-height:calc(100vh - 175px);max-width:100%!important}.match-controls{padding-top:5px}.match-controls>div{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));width:100%}.speed{font-size:11px!important;padding:7px 2px!important;margin:0 2px!important}.hud{margin-top:8px}}
`;
function installStyle(){if(document.querySelector('style[data-argentina-ui-v1]'))return;const s=document.createElement('style');s.dataset.argentinaUiV1='1';s.textContent=CSS;document.head.appendChild(s);}
const exact=new Map([['Build','Estilo'],['Build inicial','Estilo de juego'],['Entrenar','Entrenamiento'],['PvP Async','Desafíos'],['Nueva carrera','Nueva partida'],['MATCHDAY','FECHA'],['RATING','PUNTAJE'],['DATOS','DATOS DEL JUEGO'],['Fuentes','Fuentes de datos'],['Mi jugador','Mi futbolista'],['Jugar 11v11','Jugar partido'],['PARTIDO EN VIVO','PARTIDO'],['MODO CARRERA · 11 CONTRA 11','MODO CARRERA · FÚTBOL ARGENTINO'],['Bronze','Bronce'],['Silver','Plata'],['Gold','Oro']]);
function localize(root=document){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){const raw=n.nodeValue,trim=raw.trim();if(!trim)continue;if(exact.has(trim)){n.nodeValue=raw.replace(trim,exact.get(trim));continue;}n.nodeValue=n.nodeValue.replace(/\bBuild base:/g,'Estilo base:').replace(/\bBuild\b/g,'Estilo').replace(/\bfans\b/gi,'hinchas').replace(/\bScout\b/g,'Visor').replace(/\bscouts\b/gi,'visores').replace(/\bdrills\b/gi,'ejercicios').replace(/\bRating temp\./g,'Puntaje prom.').replace(/\bMOTM\b/g,'Figura').replace(/\bAsist\./g,'Asist.').replace(/\bIntercep\./g,'Cortes').replace(/\bGhost XI\b/g,'Equipo desafío');}}
function addToggle(){const top=document.querySelector('.top');if(!top||document.querySelector('#argNavToggle'))return;const b=document.createElement('button');b.id='argNavToggle';b.className='arg-nav-toggle';b.type='button';b.title='Contraer o expandir menú';b.textContent=collapsed?'☰':'⇤';b.onclick=()=>{collapsed=!collapsed;try{localStorage.setItem(NAV_KEY,collapsed?'1':'0');}catch{}decorate();};top.insertBefore(b,top.firstChild);}
function filterBuilds(){const pos=document.querySelector('#position')?.value;if(!pos)return;const allowed=new Set(buildsForPosition(pos).map(b=>b.id)),buttons=[...document.querySelectorAll('[data-build]')];for(const b of buttons)b.dataset.buildHidden=allowed.has(b.dataset.build)?'0':'1';const selected=buttons.find(b=>b.classList.contains('selected'));if(selected&&!allowed.has(selected.dataset.build))buttons.find(b=>allowed.has(b.dataset.build))?.click();}
function forceOpeningSpeed(){if(!matchStartPending||!document.querySelector('#canvas'))return;const one=document.querySelector('[data-speed="1"]');if(one&&!one.classList.contains('on'))one.click();matchStartPending=false;}
function decorate(){installStyle();document.documentElement.lang='es-AR';document.title='Career Eleven · Fútbol Argentino';const shell=document.querySelector('.shell');if(shell)shell.classList.toggle('nav-collapsed',collapsed);document.body.classList.toggle('match-live-active',!!document.querySelector('#canvas'));addToggle();filterBuilds();localize(document.querySelector('#app')||document);forceOpeningSpeed();}
document.addEventListener('click',e=>{if(e.target.closest?.('#kickoff,#asyncPlay'))matchStartPending=true;},true);document.addEventListener('change',e=>{if(e.target?.id==='position')setTimeout(filterBuilds,0);},true);new MutationObserver(()=>decorate()).observe(document.querySelector('#app')||document.body,{childList:true,subtree:true});decorate();
export const __argentinaUiV1={filterBuilds,decorate};
