import {COUNTRIES,SOURCE_PLAYERS,OPEN_NAMES,BUILDS,SKILLS,FORMATIONS} from './data.js';
import {createDevelopmentProfile,scaleAttributesToDevelopmentLevel} from './career-development.js';
import {initializeCareerTime,advanceCareerDays,rollCareerToSeasonStart} from './career-time-v1.js';

export const CAREER_VERSION=4;
export const STORE_KEY='career-eleven-2d:v4';

export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function seeded(seed){let h=2166136261;for(const ch of String(seed)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
export function clubById(id){for(const country of COUNTRIES)for(const club of country.clubs)if(club.id===id)return club;return null;}
export function countryById(id){return COUNTRIES.find(c=>c.id===id)||null;}
export function buildById(id){return BUILDS.find(b=>b.id===id)||BUILDS[0];}
export function skillById(id){return SKILLS.find(s=>s.id===id)||null;}

const POSITION_BASE={
  GK:{pace:56,shooting:30,passing:64,dribbling:49,defense:77,physical:72,ballControl:65,vision:69,stamina:65,composure:75},
  ST:{pace:72,shooting:75,passing:62,dribbling:70,defense:34,physical:70,ballControl:71,vision:62,stamina:70,composure:72},
  LW:{pace:78,shooting:68,passing:68,dribbling:76,defense:38,physical:60,ballControl:75,vision:68,stamina:72,composure:67},
  RW:{pace:78,shooting:68,passing:68,dribbling:76,defense:38,physical:60,ballControl:75,vision:68,stamina:72,composure:67},
  CAM:{pace:69,shooting:68,passing:76,dribbling:75,defense:45,physical:58,ballControl:77,vision:78,stamina:70,composure:72},
  CM:{pace:66,shooting:63,passing:75,dribbling:70,defense:62,physical:66,ballControl:73,vision:74,stamina:78,composure:70},
  CDM:{pace:64,shooting:55,passing:70,dribbling:64,defense:75,physical:75,ballControl:68,vision:68,stamina:80,composure:70},
  LB:{pace:75,shooting:48,passing:67,dribbling:68,defense:72,physical:70,ballControl:67,vision:62,stamina:81,composure:65},
  RB:{pace:75,shooting:48,passing:67,dribbling:68,defense:72,physical:70,ballControl:67,vision:62,stamina:81,composure:65},
  CB:{pace:64,shooting:40,passing:61,dribbling:55,defense:78,physical:80,ballControl:61,vision:58,stamina:72,composure:72},
};

const BUILD_START_SKILL={finisher:'finesse',creator:'threaded-pass',technician:'technical',engine:'relentless','ball-winner':'interceptor',speedster:'quick-step',target:'aerial','shot-stopper':'keeper-reflex','sweeper-keeper':'sweeper-reader','keeper-playmaker':'keeper-pass'};

function uid(prefix,r=Math.random){return `${prefix}-${Math.floor(r()*1e9).toString(36)}-${Math.floor(r()*1e6).toString(36)}`;}
function rawToPlayer(raw,seedKey){const r=seeded(seedKey);const ballControl=clamp(Math.round((raw.dribbling*1.15+raw.passing*.35+raw.rating*.5)/2),35,96);const vision=clamp(Math.round(raw.passing*.75+raw.rating*.25+(r()-.5)*4),35,96);const stamina=clamp(Math.round(raw.physical*.55+raw.pace*.25+raw.rating*.2),40,96);const composure=clamp(Math.round(raw.rating*.55+raw.shooting*.35+raw.dribbling*.1),40,96);return {...raw,instanceId:uid('p',r),ballControl,vision,stamina,composure,potential:clamp(raw.rating+Math.round(r()*8)-(raw.age>29?4:0),raw.rating,96),fitness:100,form:0,isUser:false};}

function positionCycle(i){return ['GK','GK','LB','CB','CB','CB','RB','CDM','CM','CM','CAM','LW','RW','ST','ST','LB','RB','CM','LW','RW','ST','CDM'][i%22];}
function generatedPlayer(name,club,index,season=1){const r=seeded(`${club.id}-${season}-${index}-${name}`);const position=positionCycle(index);const base=clamp(Math.round(club.reputation-12+(r()-.5)*12),58,90);const age=18+Math.floor(r()*15);const mod=(kind)=>{let v=base+(r()-.5)*16;if(['LB','RB','LW','RW'].includes(position)&&kind==='pace')v+=7;if(['ST','LW','RW','CAM'].includes(position)&&kind==='shooting')v+=6;if(['CM','CAM','CDM'].includes(position)&&kind==='passing')v+=6;if(['LW','RW','CAM'].includes(position)&&kind==='dribbling')v+=7;if(['CB','LB','RB','CDM','GK'].includes(position)&&kind==='defense')v+=8;if(['CB','CDM','ST','GK'].includes(position)&&kind==='physical')v+=7;if(position==='GK'){if(kind==='defense')v+=8;if(kind==='shooting')v-=22;if(kind==='dribbling')v-=8;}return clamp(Math.round(v),35,95);};const raw={id:`gen-${club.id}-${season}-${index}`,name,team:club.name,country:countryById(club.country)?.name||club.country,rating:base,position,pace:mod('pace'),shooting:mod('shooting'),passing:mod('passing'),dribbling:mod('dribbling'),defense:mod('defense'),physical:mod('physical'),age,source:'openfootball-name-generated-ratings'};return rawToPlayer(raw,`${club.id}-${name}-${season}`);}

function namePool(countryId,season){const primary=OPEN_NAMES[countryId]||OPEN_NAMES.EN;const all=[...primary];for(const [key,names] of Object.entries(OPEN_NAMES))if(key!==countryId)all.push(...names);const r=seeded(`names-${countryId}-${season}`);for(let i=all.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[all[i],all[j]]=[all[j],all[i]];}return all;}
function makeRoster(club,index,season=1){const exact=SOURCE_PLAYERS.filter(p=>slug(p.team)===slug(club.name)).map((p,i)=>rawToPlayer(p,`${club.id}-source-${i}`));const pool=namePool(club.country,season);const roster=[...exact];let cursor=index*23;while(roster.length<22){let name=pool[cursor%pool.length]||`Juvenil ${cursor+1}`;if(roster.some(p=>p.name===name))name=`${name} ${String.fromCharCode(65+(cursor%20))}`;roster.push(generatedPlayer(name,club,roster.length,season));cursor++;}return roster.slice(0,24);}

function positionWeights(pos){const map={
  GK:{defense:.30,composure:.18,physical:.14,ballControl:.12,vision:.10,passing:.08,pace:.04,stamina:.04},
  ST:{shooting:.29,pace:.16,dribbling:.16,ballControl:.14,composure:.13,physical:.08,passing:.04},LW:{pace:.23,dribbling:.22,ballControl:.15,shooting:.14,passing:.10,vision:.07,stamina:.05,composure:.04},RW:{pace:.23,dribbling:.22,ballControl:.15,shooting:.14,passing:.10,vision:.07,stamina:.05,composure:.04},CAM:{passing:.20,vision:.18,dribbling:.17,ballControl:.17,shooting:.11,composure:.08,pace:.05,stamina:.04},CM:{passing:.18,vision:.14,ballControl:.13,stamina:.13,dribbling:.10,defense:.10,physical:.09,composure:.07,pace:.04,shooting:.02},CDM:{defense:.22,physical:.17,stamina:.15,passing:.13,ballControl:.09,vision:.08,composure:.07,pace:.05,dribbling:.04},LB:{pace:.18,stamina:.17,defense:.17,physical:.13,passing:.12,dribbling:.09,ballControl:.07,vision:.04,composure:.03},RB:{pace:.18,stamina:.17,defense:.17,physical:.13,passing:.12,dribbling:.09,ballControl:.07,vision:.04,composure:.03},CB:{defense:.29,physical:.24,composure:.12,pace:.10,stamina:.08,passing:.07,ballControl:.05,vision:.03,dribbling:.02},
  };return map[pos]||map.CM;}
export function calculateOverall(player){const w=positionWeights(player.position);let sum=0,total=0;for(const [k,v] of Object.entries(w)){sum+=(player[k]||50)*v;total+=v;}return clamp(Math.round(sum/total),40,99);}

export function createUserPlayer({name,nationality,position,build,development=true,developmentSeed}){const b=buildById(build);const base={...(POSITION_BASE[position]||POSITION_BASE.CM)};for(const [k,v] of Object.entries(b.mods||{}))base[k]=clamp((base[k]??65)+v,35,92);let profile=null;if(development!==false){const config=typeof development==='object'?development:{};profile=createDevelopmentProfile({seed:config.seed||developmentSeed||`${name}|${nationality}|${position}|${b.id}`,age:config.age??17,entryLevel:config.entryLevel||'reserve',background:config.background||'local_academy'});Object.assign(base,scaleAttributesToDevelopmentLevel(base,profile.startingOverall,position));}const startSkill=BUILD_START_SKILL[b.id]||'first-touch',player={id:'user-player',instanceId:'user-player',name:(name||'').trim()||'Jugador',team:'',country:countryById(nationality)?.name||nationality,position,age:profile?.age??18,birthDate:profile?.birthDate??null,source:'career-created',isUser:true,build:b.id,skills:[startSkill],unlockedSkills:[startSkill],instructions:{risk:55,shoot:55,dribble:60},fitness:100,form:0,potential:profile?.potential??96,dynamicPotential:profile?.dynamicPotential??96,developmentProfile:profile,...base};player.rating=calculateOverall(player);return player;}

function defaultTeamTactics(club){const r=seeded(`team-style-${club.id}`);return{formation:['4-3-3','4-2-3-1','4-4-2'][Math.floor(r()*3)],pressing:45+Math.round(r()*30),tempo:45+Math.round(r()*30),width:44+Math.round(r()*25),directness:40+Math.round(r()*35)};}

export function createCareer(input){const country=countryById(input.countryId),club=clubById(input.clubId);if(!country||!club)throw new Error('Club o país inválido');const development={age:input.age??17,entryLevel:input.entryLevel||'reserve',background:input.background||'local_academy',seed:`career|${(input.playerName||'Jugador').trim()}|${input.nationality||country.id}|${input.position||'CM'}|${input.build||'creator'}|${club.id}`};const player=createUserPlayer({name:input.playerName,nationality:input.nationality||country.id,position:input.position||'CM',build:input.build||'creator',development});player.team=club.name;const world={};country.clubs.forEach((c,i)=>{world[c.id]={clubId:c.id,roster:makeRoster(c,i,1),tactics:defaultTeamTactics(c)};});const own=world[club.id].roster;const same=own.filter(p=>p.position===player.position&&!p.isUser).sort((a,b)=>a.rating-b.rating);if(same.length){const remove=same[0];world[club.id].roster=own.filter(p=>p.instanceId!==remove.instanceId);}world[club.id].roster.push(player);
  const state={version:CAREER_VERSION,createdAt:Date.now(),countryId:country.id,clubId:club.id,season:1,week:1,world,player,progress:{level:1,xp:0,nextXp:300,skillPoints:1,trainingPoints:2,reputation:10,fans:1200},seasonStats:freshSeasonStats(),schedule:makeRoundRobin(country.id,1),table:initTable(country.id),history:[],lastMatch:null,seasonComplete:false,asyncLeague:{rating:1000,division:'Bronce',record:{w:0,d:0,l:0},opponents:makeGhostOpponents(country.id,club.id,1000,1)},settings:{camera:'player',speed:1}};initializeCareerTime(state);return state;}
function freshSeasonStats(){return{apps:0,goals:0,assists:0,avgRating:0,passes:0,passPct:0,dribbles:0,dribblePct:0,tackles:0,interceptions:0,shots:0,motm:0};}

export function initTable(countryId){return countryById(countryId).clubs.map(c=>({clubId:c.id,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0}));}
export function makeRoundRobin(countryId,season=1){const ids=countryById(countryId).clubs.map(c=>c.id),arr=[...ids];if(arr.length%2)arr.push(null);const n=arr.length,first=[];let rot=[...arr];for(let r=0;r<n-1;r++){const fixtures=[];for(let i=0;i<n/2;i++){const a=rot[i],b=rot[n-1-i];if(a&&b){const swap=(r+i+season)%2===1;fixtures.push({id:`s${season}-r${r+1}-${i}`,home:swap?b:a,away:swap?a:b,played:false,score:null});}}first.push({week:r+1,fixtures});rot=[rot[0],rot[n-1],...rot.slice(1,n-1)];}const second=first.map((round,i)=>({week:first.length+i+1,fixtures:round.fixtures.map((f,j)=>({id:`s${season}-r${first.length+i+1}-${j}`,home:f.away,away:f.home,played:false,score:null}))}));return[...first,...second];}
export function nextFixture(state){for(const round of state.schedule){const f=round.fixtures.find(x=>!x.played&&(x.home===state.clubId||x.away===state.clubId));if(f)return{...f,week:round.week};}return null;}
export function sortedTable(state){return[...state.table].sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf);}
export function leaguePosition(state){return sortedTable(state).findIndex(r=>r.clubId===state.clubId)+1;}

function posFamily(p){if(p==='GK')return'GK';if(['CB','LB','RB','LWB','RWB'].includes(p))return'DEF';if(['CDM','CM','CAM','LM','RM'].includes(p))return'MID';return'FWD';}
function fitForSlot(player,slot){if(slot==='GK')return player.position==='GK'?100+player.rating+(player.form||0)+(player.fitness-80)*.04:-100;const fam=posFamily(player.position),sf=posFamily(slot);let fit=fam===sf?35:-10;if(player.position===slot)fit+=25;if(slot==='CM'&&['CAM','CDM'].includes(player.position))fit+=12;if(['LW','RW'].includes(slot)&&['LW','RW','ST'].includes(player.position))fit+=10;if(slot==='ST'&&['LW','RW'].includes(player.position))fit+=6;if(['LB','RB'].includes(slot)&&player.position==='CB')fit+=5;return fit+player.rating+(player.form||0)+(player.fitness-80)*.04;}
function pickStartingEleven(state,clubId){const club=state.world[clubId],formation=FORMATIONS[club.tactics.formation]||FORMATIONS['4-3-3'];const available=[...club.roster].filter(p=>(p.fitness??100)>20);const used=new Set(),lineup=[];for(const slot of formation.slots){const candidates=available.filter(p=>!used.has(p.instanceId)).sort((a,b)=>fitForSlot(b,slot)-fitForSlot(a,slot));const pick=candidates[0];if(pick){used.add(pick.instanceId);lineup.push({...pick,engineRole:slot});}}return lineup.slice(0,11);}
function bestBenchRole(player,slots){let best=slots[0]||player.position,score=-Infinity;for(const slot of slots){const value=fitForSlot(player,slot);if(value>score){best=slot;score=value;}}return{role:best,score};}
export function matchdaySelection(state,clubId=state.clubId){const club=state.world[clubId],formation=FORMATIONS[club.tactics.formation]||FORMATIONS['4-3-3'],starters=pickStartingEleven(state,clubId),used=new Set(starters.map(p=>p.instanceId));const available=club.roster.filter(p=>(p.fitness??100)>20&&!used.has(p.instanceId));const bench=available.map(p=>{const fit=bestBenchRole(p,formation.slots);return{...p,engineRole:fit.role,_selectionScore:fit.score};}).sort((a,b)=>b._selectionScore-a._selectionScore).slice(0,7).map(({_selectionScore,...p})=>p);const user=club.roster.find(p=>p.isUser);let status='reserve';if(user){if(starters.some(p=>p.instanceId===user.instanceId))status='starter';else if(bench.some(p=>p.instanceId===user.instanceId))status='bench';}return{starters,bench,status,user};}
export function lineup11(state,clubId,options={}){const selection=matchdaySelection(state,clubId),lineup=[...selection.starters];if(options.forceUser&&clubId===state.clubId&&!lineup.some(p=>p.isUser)){const user=state.world[clubId].roster.find(p=>p.isUser);if(user){let replace=user.position==='GK'?lineup.findIndex(p=>p.engineRole==='GK'):lineup.findIndex(p=>p.engineRole!=='GK'&&posFamily(p.engineRole)===posFamily(user.position));if(replace<0)replace=lineup.length-1;lineup[replace]={...user,engineRole:user.position==='GK'?'GK':(lineup[replace]?.engineRole||user.position)};}}return lineup.slice(0,11);}
export function clubStrength(state,clubId){const xi=lineup11(state,clubId);return xi.reduce((s,p)=>s+p.rating+(p.form||0),0)/Math.max(1,xi.length);}

function applyTable(state,home,away,hg,ag){const h=state.table.find(r=>r.clubId===home),a=state.table.find(r=>r.clubId===away);h.p++;a.p++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.w++;a.l++;h.pts+=3;}else if(ag>hg){a.w++;h.l++;a.pts+=3;}else{h.d++;a.d++;h.pts++;a.pts++;}}
function poisson(lambda,r){let L=Math.exp(-lambda),k=0,p=1;do{k++;p*=r();}while(p>L&&k<9);return k-1;}
function simulateOther(state,f){const r=seeded(`${state.season}-${f.id}`),h=clubStrength(state,f.home),a=clubStrength(state,f.away);return[poisson(clamp(1.25+(h-a)*.055+.18,.25,3.7),r),poisson(clamp(1.08+(a-h)*.055,.2,3.5),r)];}

export function completeCareerMatch(state,fixtureId,report){const round=state.schedule.find(r=>r.fixtures.some(f=>f.id===fixtureId)),f=round?.fixtures.find(x=>x.id===fixtureId);if(!f||f.played)return{ok:false,message:'Partido no disponible'};const selection=matchdaySelection(state,state.clubId),score=report.score||[0,0],matchDate=state.clock?.currentDate||null;f.played=true;f.score=[score[0],score[1]];applyTable(state,f.home,f.away,score[0],score[1]);for(const other of round.fixtures){if(other.played)continue;const s=simulateOther(state,other);other.played=true;other.score=s;applyTable(state,other.home,other.away,s[0],s[1]);}
  const perf=report.userPerformance??null;if(perf)applyPerformance(state,perf);state.lastMatch={fixtureId,date:matchDate,score:[...score],opponent:f.home===state.clubId?f.away:f.home,userPerformance:perf,squadStatus:selection.status};state.history.push({season:state.season,week:state.week,date:matchDate,score:[...score],appeared:Boolean(perf),squadStatus:selection.status,rating:perf?.rating??null,goals:perf?.goals||0,assists:perf?.assists||0});recoverWorld(state);advanceCareerDays(state,7);state.week++;state.progress.trainingPoints=2;if(state.week>state.schedule.length){state.seasonComplete=true;state.progress.reputation+=Math.max(1,7-leaguePosition(state));}return{ok:true,message:perf?'Partido guardado':selection.status==='bench'?'Partido guardado · quedaste en el banco':'Partido guardado · no fuiste convocado'};}

function applyPerformance(state,p){const s=state.seasonStats;s.apps++;s.goals+=p.goals||0;s.assists+=p.assists||0;s.shots+=p.shots||0;s.tackles+=p.tackles||0;s.interceptions+=p.interceptions||0;s.passes+=p.passesAttempted||0;s.dribbles+=p.dribblesAttempted||0;const oldApps=s.apps-1;s.avgRating=((s.avgRating*oldApps)+(p.rating||6))/s.apps;s.passPct=((s.passPct*oldApps)+(p.passesAttempted?100*(p.passesCompleted||0)/p.passesAttempted:0))/s.apps;s.dribblePct=((s.dribblePct*oldApps)+(p.dribblesAttempted?100*(p.dribblesCompleted||0)/p.dribblesAttempted:0))/s.apps;if((p.rating||0)>=8.5)s.motm++;
  const xp=Math.round(55+(p.rating||6)*16+(p.goals||0)*85+(p.assists||0)*60+(p.dribblesCompleted||0)*6+(p.interceptions||0)*5+(p.saves||0)*7);grantXP(state,xp);state.progress.fans+=Math.max(0,Math.round(((p.rating||6)-5.8)*75+(p.goals||0)*120));state.player.form=clamp(Math.round(((p.rating||6)-6)*1.5),-3,5);state.player.fitness=clamp(100-(p.staminaUsed||15),45,100);}
function grantXP(state,amount){state.progress.xp+=amount;while(state.progress.xp>=state.progress.nextXp){state.progress.xp-=state.progress.nextXp;state.progress.level++;state.progress.nextXp=Math.round(state.progress.nextXp*1.12);state.progress.skillPoints++;state.progress.trainingPoints++;}}
function recoverWorld(state){for(const world of Object.values(state.world))for(const p of world.roster){p.fitness=clamp((p.fitness??100)+18,40,100);if(!p.isUser&&p.age<25&&p.rating<p.potential&&seeded(`${state.season}-${state.week}-${p.instanceId}`)()<.018){p.rating++;}}state.player.fitness=clamp(state.player.fitness+16,45,100);}

export function trainAttribute(state,attr){if(state.progress.trainingPoints<=0)return{ok:false,message:'No quedan sesiones esta semana'};if(!(attr in state.player)||typeof state.player[attr]!=='number')return{ok:false,message:'Atributo inválido'};if(state.player[attr]>=99)return{ok:false,message:'Atributo al máximo'};const gain=state.player[attr]<70?2:1;state.player[attr]=clamp(state.player[attr]+gain,30,99);state.player.rating=calculateOverall(state.player);state.progress.trainingPoints--;grantXP(state,25);syncUserPlayer(state);return{ok:true,gain};}
export function unlockSkill(state,skillId){const skill=skillById(skillId);if(!skill)return{ok:false,message:'Habilidad inválida'};if(state.player.unlockedSkills.includes(skillId))return toggleSkill(state,skillId);if(state.progress.skillPoints<1)return{ok:false,message:'Necesitás un punto de habilidad'};state.progress.skillPoints--;state.player.unlockedSkills.push(skillId);if(state.player.skills.length<3)state.player.skills.push(skillId);syncUserPlayer(state);return{ok:true,message:`${skill.name} desbloqueado`};}
export function toggleSkill(state,skillId){if(!state.player.unlockedSkills.includes(skillId))return{ok:false,message:'No desbloqueada'};const i=state.player.skills.indexOf(skillId);if(i>=0){state.player.skills.splice(i,1);return{ok:true,message:'Habilidad desequipada'};}if(state.player.skills.length>=3)return{ok:false,message:'Máximo 3 habilidades equipadas'};state.player.skills.push(skillId);return{ok:true,message:'Habilidad equipada'};}
export function setInstruction(state,key,value){if(!['risk','shoot','dribble'].includes(key))return;state.player.instructions[key]=clamp(Number(value)||50,0,100);syncUserPlayer(state);}
function syncUserPlayer(state){const roster=state.world[state.clubId].roster,idx=roster.findIndex(p=>p.isUser);if(idx>=0)roster[idx]=state.player;}

export function startNextSeason(state){if(!state.seasonComplete)return{ok:false,message:'La temporada sigue activa'};state.season++;state.week=1;state.seasonComplete=false;state.schedule=makeRoundRobin(state.countryId,state.season);state.table=initTable(state.countryId);state.seasonStats=freshSeasonStats();rollCareerToSeasonStart(state,state.season);state.player.form=0;state.player.fitness=100;state.progress.trainingPoints=3;state.asyncLeague.opponents=makeGhostOpponents(state.countryId,state.clubId,state.asyncLeague.rating,state.season);for(const world of Object.values(state.world))for(const p of world.roster){p.form=0;p.fitness=100;}return{ok:true};}

export function makeGhostOpponents(countryId,userClubId,rating,season){const names=['Nova','Kairo','Mauro','Lynx','Santos','Raven','Ivo','Mika'];const builds=BUILDS.filter(b=>!(Array.isArray(b.positions)&&b.positions.includes('GK'))).map(b=>b.id);const positions=['ST','RW','CAM','CM','LW','CDM'];const clubs=countryById(countryId).clubs.filter(c=>c.id!==userClubId);const r=seeded(`ghosts-${countryId}-${rating}-${season}`);return Array.from({length:5},(_,i)=>{const elo=Math.round(rating-90+r()*180);const build=builds[Math.floor(r()*builds.length)],position=positions[Math.floor(r()*positions.length)];const ghost=createUserPlayer({name:names[(i+season)%names.length],nationality:countryId,position,build,development:false});const boost=clamp(Math.round((elo-1000)/35),-5,8);for(const k of ['pace','shooting','passing','dribbling','defense','physical','ballControl','vision','stamina','composure'])ghost[k]=clamp(ghost[k]+boost,35,96);ghost.rating=calculateOverall(ghost);ghost.instanceId=`ghost-${season}-${i}`;ghost.id=ghost.instanceId;ghost.isUser=false;ghost.isGhost=true;ghost.skills=[BUILD_START_SKILL[build]||'first-touch'];return{id:`opp-${season}-${i}`,name:ghost.name,elo,clubId:clubs[i%clubs.length].id,player:ghost,played:false};});}
export function asyncOpponent(state,id){return state.asyncLeague.opponents.find(o=>o.id===id)||null;}
export function asyncLineup(state,opponentId){const opp=asyncOpponent(state,opponentId);if(!opp)return null;const world=state.world[opp.clubId],clone={...state,world:{...state.world,[opp.clubId]:{...world,roster:[...world.roster]}}};const ghost={...opp.player,team:clubById(opp.clubId).name};const same=clone.world[opp.clubId].roster.filter(p=>p.position===ghost.position).sort((a,b)=>a.rating-b.rating)[0];if(same)clone.world[opp.clubId].roster=clone.world[opp.clubId].roster.filter(p=>p.instanceId!==same.instanceId);clone.world[opp.clubId].roster.push(ghost);const xi=lineup11(clone,opp.clubId);if(!xi.some(p=>p.instanceId===ghost.instanceId)){let replace=xi.findIndex(p=>p.engineRole!=='GK'&&posFamily(p.engineRole)===posFamily(ghost.position));if(replace<0)replace=xi.length-1;xi[replace]={...ghost,engineRole:xi[replace]?.engineRole||ghost.position};}return xi;}
export function recordAsyncResult(state,opponentId,score,userPerformance){const opp=asyncOpponent(state,opponentId);if(!opp||opp.played)return{ok:false};const gf=score[0],ga=score[1];let delta=0;if(gf>ga){state.asyncLeague.record.w++;delta=24;}else if(gf===ga){state.asyncLeague.record.d++;delta=4;}else{state.asyncLeague.record.l++;delta=-18;}delta+=Math.round(((userPerformance?.rating||6)-6)*2);state.asyncLeague.rating=clamp(state.asyncLeague.rating+delta,600,2200);state.asyncLeague.division=state.asyncLeague.rating>=1800?'Elite':state.asyncLeague.rating>=1500?'Oro':state.asyncLeague.rating>=1200?'Plata':'Bronce';opp.played=true;grantXP(state,Math.max(25,60+delta));return{ok:true,delta};}

export function saveCareer(state){syncUserPlayer(state);localStorage.setItem(STORE_KEY,JSON.stringify(state));}
export function loadCareer(){try{const raw=JSON.parse(localStorage.getItem(STORE_KEY));if(!raw||raw.version!==CAREER_VERSION)return null;raw.settings??={camera:'player',speed:1};raw.settings.speed=1;if(!raw.clock)initializeCareerTime(raw);return raw;}catch{return null;}}
export function clearCareer(){localStorage.removeItem(STORE_KEY);}
