import { COUNTRIES, SOURCE_PLAYERS, OPEN_NAMES, STAFF_NAMES, STAFF_ROLES, SPONSORS, NARRATIVE_EVENTS, MANAGER_STYLES } from './data.js';

export const CAREER_VERSION=3;
export const STORE_KEY='haxball-manager-2d:v3';

export function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
export function clubById(id){for(const c of COUNTRIES)for(const club of c.clubs)if(club.id===id)return club;return null;}
export function countryById(id){return COUNTRIES.find(c=>c.id===id)||null;}
export function styleById(id){return MANAGER_STYLES.find(s=>s.id===id)||MANAGER_STYLES[0];}
export function seeded(seed){let h=2166136261;for(const ch of String(seed)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export function uid(prefix='id',r=Math.random){return `${prefix}-${Math.floor(r()*1e9).toString(36)}-${Date.now().toString(36).slice(-4)}`;}
export function slugTeam(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}

function playerValue(rating,age,potential=rating){const peak=Math.max(rating,potential*.86);const ageFactor=age<=22?1.32:age<=26?1.15:age<=30?1:age<=33?.78:.52;return Math.round(Math.max(.5,Math.pow(Math.max(4,peak-56),1.72)/13*ageFactor)*10)/10;}
function defaultWage(value,rating){return Math.max(8,Math.round(value*1.8+Math.max(0,rating-75)*2.2));}
function positionGroup(pos){if(pos==='GK')return'GK';if(['CB','LB','RB','LWB','RWB'].includes(pos))return'DEF';if(['CDM','CM','CAM','LM','RM'].includes(pos))return'MID';return'FWD';}
function keyAttribute(position){const g=positionGroup(position);return g==='GK'?'defense':g==='DEF'?'defense':g==='MID'?'passing':'shooting';}
function decoratePlayer(raw,seedKey,sourceGenerated=false){const r=seeded(seedKey);const potential=clamp(Math.max(raw.rating,Math.round(raw.rating+(r()*12)-(raw.age>28?4:0))),raw.rating,96);const value=playerValue(raw.rating,raw.age,potential);return {...raw,instanceId:uid('p',r),generated:sourceGenerated,potential,value,form:0,injury:0,suspended:0,listed:false,scouted:raw.source==='fc26-pl-cc0',contract:{years:2+Math.floor(r()*4),wage:defaultWage(value,raw.rating),morale:64+Math.round(r()*22),fitness:88+Math.round(r()*12)},stats:{apps:0,goals:0,assists:0,yellow:0,red:0,avg:0}};}
function generatedPlayer(name,club,index,season=1){const r=seeded(`${season}-${club.id}-${name}-${index}`);const positions=['GK','CB','RB','LB','CDM','CM','CAM','RW','LW','ST','ST','CB','CM','FWD'];const position=positions[index%positions.length];const rep=club.reputation;const base=clamp(Math.round(rep-15+(r()-.5)*14),58,90);const age=18+Math.floor(r()*15);const boost=(kind)=>{let v=base+(r()-.5)*18;if(kind==='defense'&&positionGroup(position)==='DEF')v+=9;if(kind==='passing'&&positionGroup(position)==='MID')v+=8;if(kind==='shooting'&&positionGroup(position)==='FWD')v+=9;if(kind==='pace'&&['RW','LW','RB','LB'].includes(position))v+=7;if(position==='GK'){if(kind==='defense')v+=11;if(kind==='shooting')v-=24;}return clamp(Math.round(v),38,95);};const raw={id:`gen-${club.id}-${season}-${index}`,name,team:club.name,country:countryById(club.country)?.name||club.country,rating:base,position,pace:boost('pace'),shooting:boost('shooting'),passing:boost('passing'),dribbling:boost('dribbling'),defense:boost('defense'),physical:boost('physical'),age,source:'openfootball-name-generated-ratings'};return decoratePlayer(raw,`${club.id}-${name}-${season}`,true);}

function namePoolForLeague(countryId,season){const all=[];for(const [country,names] of Object.entries(OPEN_NAMES))for(const name of names)all.push({name,country});const r=seeded(`league-names-${countryId}-${season}`);for(let i=all.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[all[i],all[j]]=[all[j],all[i]];}return all;}
function initialSquad(club,index,season=1,namePool=[]){const exact=SOURCE_PLAYERS.filter(p=>slugTeam(p.team)===slugTeam(club.name)).map((p,i)=>decoratePlayer(p,`${club.id}-source-${i}-${season}`,false));const squad=[...exact];let cursor=index*17;while(squad.length<14){const info=namePool[cursor%namePool.length]||{name:`Academy Player ${cursor+1}`};let name=info.name;if(squad.some(p=>p.name===name))name=`${name} ${String.fromCharCode(65+(cursor%20))}`;squad.push(generatedPlayer(name,club,squad.length,season));cursor++;}return squad.slice(0,16);}
function baseTactics(club){const r=seeded(`tactics-${club.id}`);const formations=['1-2-1','2-1-1','1-1-2'];const mentalities=['Defensive','Balanced','Attacking'];const passing=['Direct','Balanced','Short'];return{formation:formations[Math.floor(r()*formations.length)],mentality:mentalities[Math.floor(r()*mentalities.length)],pressing:45+Math.round(r()*35),tempo:45+Math.round(r()*35),width:40+Math.round(r()*35),passing:passing[Math.floor(r()*passing.length)]};}
function staffRatingFor(club){return clamp(Math.round(48+club.reputation*.43),58,91);}
function defaultUserStaff(club){const r=seeded(`staff-${club.id}`);return STAFF_ROLES.map((x,i)=>({id:uid('staff',r),role:x.role,name:STAFF_NAMES[(i*2+Math.floor(r()*STAFF_NAMES.length))%STAFF_NAMES.length],rating:clamp(Math.round(56+club.reputation*.2+r()*14),58,86),wage:Math.round(x.baseWage*(.75+club.reputation/180))}));}
function defaultTraining(){return{focus:'Balanced',intensity:58};}

export function createCareer(input){const country=countryById(input.countryId);const selected=clubById(input.clubId);if(!country||!selected)throw new Error('Invalid country or club');const clubs={};const names=namePoolForLeague(country.id,1);country.clubs.forEach((club,i)=>{clubs[club.id]={clubId:club.id,budget:club.budget,wageBudget:Math.round(club.reputation*14),squad:initialSquad(club,i,1,names),tactics:baseTactics(club),staffRating:staffRatingFor(club)};});const state={version:CAREER_VERSION,createdAt:Date.now(),manager:{name:(input.manager||'Manager').trim()||'Manager',nationality:input.nationality||country.id,style:input.style||'tactician',reputation:38,board:72,dressingRoom:70,media:30,legacy:0,seasons:0,trophies:[],record:{w:0,d:0,l:0,gf:0,ga:0}},countryId:country.id,clubId:selected.id,season:1,week:1,budget:selected.budget,wageBudget:Math.round(selected.reputation*14),clubs,staff:defaultUserStaff(selected),staffCandidates:makeStaffCandidates(selected,1),training:defaultTraining(),trainingDoneWeek:null,tactics:{...clubs[selected.id].tactics},startingXI:[],schedule:makeRoundRobin(country.id,1),table:initTable(country.id),cup:makeCup(country.id,1),draft:{open:true,picksLeft:4,round:1,pool:makeDraftPool(country.id,1)},sponsor:{active:null,offers:sponsorOffers(selected.id,1)},currentEvent:pickNarrativeEvent(selected.id,1,1),eventResolved:false,inbox:[`Welcome to ${selected.name}. Build your squad, define an identity and survive the season.`],history:[],incomingOffers:[],scoutReports:{},scoutingPoints:4,marketRefresh:0,lastResult:null,seasonComplete:false,jobOffers:[],worldLog:[]};syncUserClub(state);state.startingXI=autoPickXI(state).map(p=>p.instanceId);return state;}

export function syncUserClub(state){const world=state.clubs[state.clubId];if(!world)return;state.budget=world.budget=state.budget??world.budget;state.wageBudget=world.wageBudget=state.wageBudget??world.wageBudget;world.tactics={...state.tactics};if(state.squad&&!world.squad)world.squad=state.squad;state.squad=world.squad;}

export function initTable(countryId){return countryById(countryId).clubs.map(c=>({clubId:c.id,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0}));}
export function makeRoundRobin(countryId,season=1){const ids=countryById(countryId).clubs.map(c=>c.id);const teams=[...ids];if(teams.length%2)teams.push(null);const n=teams.length;const rounds=[];let arr=[...teams];for(let round=0;round<n-1;round++){const fixtures=[];for(let i=0;i<n/2;i++){let a=arr[i],b=arr[n-1-i];if(a&&b){const swap=(round+i+season)%2===1;fixtures.push({id:`s${season}-r${round+1}-${i}`,home:swap?b:a,away:swap?a:b,played:false,score:null});}}rounds.push({week:round+1,fixtures});arr=[arr[0],arr[n-1],...arr.slice(1,n-1)];}
  const second=rounds.map((r,idx)=>({week:rounds.length+idx+1,fixtures:r.fixtures.map((f,i)=>({id:`s${season}-r${rounds.length+idx+1}-${i}`,home:f.away,away:f.home,played:false,score:null}))}));return[...rounds,...second];}

function makeCup(countryId,season){const clubs=countryById(countryId).clubs;const ordered=[...clubs].sort((a,b)=>b.reputation-a.reputation);const prelim=ordered.slice(2);return{season,stage:'Preliminary',champion:null,fixtures:[{id:`cup-${season}-p1`,stage:'Preliminary',home:prelim[0].id,away:prelim[3].id,played:false},{id:`cup-${season}-p2`,stage:'Preliminary',home:prelim[1].id,away:prelim[2].id,played:false}],byes:ordered.slice(0,2).map(c=>c.id),semis:[],final:null};}

function makeDraftPool(countryId,season){const clubs=countryById(countryId).clubs;const names=namePoolForLeague(countryId,season+13);const prospects=[];for(let i=0;i<14;i++){const ghost={...clubs[i%clubs.length],id:`draft-club-${i}`,name:'Academy'};const p=generatedPlayer(names[(i+season*7)%names.length].name,ghost,i,season+100);p.age=17+Math.floor(seeded(`${season}-age-${i}`)()*4);p.rating=clamp(p.rating-5+Math.floor(seeded(`${season}-rat-${i}`)()*8),59,84);p.potential=clamp(p.rating+5+Math.floor(seeded(`${season}-pot-${i}`)()*13),p.rating+2,95);p.value=playerValue(p.rating,p.age,p.potential);p.contract.wage=Math.max(5,Math.round(p.value*.8));p.source='draft-prospect-openfootball-name';prospects.push(p);}return prospects;}
function sponsorOffers(clubId,season){const r=seeded(`sponsor-${clubId}-${season}`);return[...SPONSORS].sort(()=>r()-.5).slice(0,3).map(s=>({...s,id:`${s.id}-${season}`}));}
function makeStaffCandidates(club,season){const r=seeded(`staff-candidates-${club.id}-${season}`);const list=[];for(const role of STAFF_ROLES){for(let i=0;i<2;i++){const rating=clamp(Math.round(58+club.reputation*.18+r()*18),58,94);list.push({id:uid('candidate',r),role:role.role,name:STAFF_NAMES[Math.floor(r()*STAFF_NAMES.length)],rating,wage:Math.round(role.baseWage*(.7+rating/90))});}}return list;}
function pickNarrativeEvent(clubId,season,week){const r=seeded(`event-${clubId}-${season}-${week}`);return JSON.parse(JSON.stringify(NARRATIVE_EVENTS[Math.floor(r()*NARRATIVE_EVENTS.length)]));}

export function nextUserFixture(state){for(const round of state.schedule){const fixture=round.fixtures.find(f=>(f.home===state.clubId||f.away===state.clubId)&&!f.played);if(fixture)return{...fixture,week:round.week};}return null;}
export function currentRound(state){return state.schedule.find(r=>r.week===state.week)||null;}
export function leaguePosition(state){const sorted=sortedTable(state);return sorted.findIndex(r=>r.clubId===state.clubId)+1;}
export function sortedTable(state){return[...state.table].sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||clubById(a.clubId).name.localeCompare(clubById(b.clubId).name));}
export function clubStrength(state,clubId){const c=state.clubs[clubId];const fit=[...c.squad].filter(p=>!p.injury&&!p.suspended).sort((a,b)=>playerMatchRating(b)-playerMatchRating(a)).slice(0,5);const avg=fit.reduce((s,p)=>s+playerMatchRating(p),0)/Math.max(1,fit.length);const tactical=(c.tactics?.pressing||55)*.02+(c.tactics?.tempo||55)*.015;return avg+(c.staffRating||68)*.06+tactical;}
function playerMatchRating(p){return p.rating+p.form+(p.contract.morale-70)*.035-(100-p.contract.fitness)*.05-p.injury*10;}

export function autoPickXI(state,clubId=state.clubId){const squad=state.clubs[clubId].squad.filter(p=>!p.injury&&!p.suspended);const gk=squad.filter(p=>p.position==='GK').sort((a,b)=>playerMatchRating(b)-playerMatchRating(a))[0];const out=squad.filter(p=>p!==gk).sort((a,b)=>playerMatchRating(b)-playerMatchRating(a));const chosen=[];if(gk)chosen.push(gk);chosen.push(...out.slice(0,5-chosen.length));return chosen.slice(0,5);}
export function selectedXI(state){const available=new Set(state.clubs[state.clubId].squad.filter(p=>!p.injury&&!p.suspended).map(p=>p.instanceId));const chosen=state.startingXI.filter(id=>available.has(id)).map(id=>state.squad.find(p=>p.instanceId===id)).filter(Boolean);if(chosen.length===5)return chosen;const auto=autoPickXI(state);state.startingXI=auto.map(p=>p.instanceId);return auto;}
export function setStarter(state,instanceId){const p=state.squad.find(x=>x.instanceId===instanceId);if(!p||p.injury||p.suspended)return{ok:false,message:'Player unavailable'};const ids=state.startingXI.filter(id=>id!==instanceId);if(state.startingXI.includes(instanceId)){state.startingXI=ids;return{ok:true};}if(ids.length>=5)ids.shift();ids.push(instanceId);state.startingXI=ids;return{ok:true};}

export function resolveNarrativeChoice(state,index){if(state.eventResolved||!state.currentEvent)return{ok:false,message:'Event already resolved'};const choice=state.currentEvent.choices[index];if(!choice)return{ok:false,message:'Invalid choice'};applyEffects(state,choice.effects||{});state.eventResolved=true;state.history.push({type:'decision',season:state.season,week:state.week,event:state.currentEvent.title,choice:choice.label});state.inbox.push(`${state.currentEvent.title}: ${choice.label}.`);return{ok:true,message:choice.label};}
function applyEffects(state,e){const m=state.manager;if(e.morale){m.dressingRoom=clamp(m.dressingRoom+e.morale,0,100);for(const p of state.squad)p.contract.morale=clamp(p.contract.morale+Math.round(e.morale*.6),25,100);}if(e.board)m.board=clamp(m.board+e.board,0,100);if(e.media)m.media=clamp(m.media+e.media,0,100);if(e.budget){state.budget=Math.max(0,state.budget+e.budget);state.clubs[state.clubId].budget=state.budget;}if(e.match)m.tempMatchBonus=(m.tempMatchBonus||0)+e.match;if(e.development)m.tempDevBonus=(m.tempDevBonus||0)+e.development;if(e.fitness)for(const p of state.squad)p.contract.fitness=clamp(p.contract.fitness+e.fitness,25,100);if(e.youth)m.youthMomentum=(m.youthMomentum||0)+e.youth;if(e.scouting)state.scoutingPoints+=Math.max(1,Math.round(e.scouting/2));if(e.negotiation)m.tempNegotiation=(m.tempNegotiation||0)+e.negotiation;if(e.trainingPenalty)m.trainingPenalty=(m.trainingPenalty||0)+e.trainingPenalty;}

export function runTraining(state){if(state.trainingDoneWeek===`${state.season}-${state.week}`)return{ok:false,message:'Training already completed this week'};const style=styleById(state.manager.style);const coach=getStaff(state,'Head Coach')?.rating||60;const physio=getStaff(state,'Physio')?.rating||60;const intensity=state.training.intensity;const focus=state.training.focus;const r=seeded(`train-${state.clubId}-${state.season}-${state.week}-${focus}-${intensity}`);let improved=0,injuries=0;for(const p of state.squad){if(p.injury){p.contract.fitness=clamp(p.contract.fitness+4+physio/18,0,100);continue;}const ageFactor=p.age<=22?1.4:p.age<=27?1:p.age<=30?.6:.2;const devChance=.035+(coach/100)*.045+(style.bonus.development||0)/500+(state.manager.tempDevBonus||0)/800;const intensityFactor=.65+intensity/100;const attrs=trainingAttrs(focus,p);if(r()<devChance*ageFactor*intensityFactor){const attr=attrs[Math.floor(r()*attrs.length)];p[attr]=clamp(p[attr]+1,25,99);if(r()<.45&&p.rating<p.potential)p.rating=clamp(p.rating+1,40,p.potential);p.value=playerValue(p.rating,p.age,p.potential);improved++;}const fatigue=2+intensity*.075+(state.manager.trainingPenalty||0);p.contract.fitness=clamp(p.contract.fitness-fatigue,35,100);const injuryRisk=Math.max(.002,(intensity-55)/1300+(100-physio)/8000);if(r()<injuryRisk){p.injury=1+Math.floor(r()*4);injuries++;}}
  state.trainingDoneWeek=`${state.season}-${state.week}`;state.manager.tempDevBonus=0;state.manager.trainingPenalty=0;state.inbox.push(`Training: ${improved} player improvements${injuries?`, ${injuries} injury cases`:''}.`);return{ok:true,improved,injuries};}
function trainingAttrs(focus,p){const map={Balanced:['pace','shooting','passing','dribbling','defense','physical'],Pace:['pace','physical'],Attack:['shooting','dribbling'],Passing:['passing','dribbling'],Dribbling:['dribbling','pace'],Defence:['defense','physical'],Physical:['physical','pace']};const list=[...(map[focus]||map.Balanced)];if(focus==='Balanced')list.push(keyAttribute(p.position));return list;}
function trainAIClubs(state){for(const [clubId,c] of Object.entries(state.clubs)){if(clubId===state.clubId)continue;const r=seeded(`ai-train-${clubId}-${state.season}-${state.week}`);for(const p of c.squad){if(p.injury){p.injury=Math.max(0,p.injury-1);p.contract.fitness=clamp(p.contract.fitness+8,50,100);continue;}p.contract.fitness=clamp(p.contract.fitness+6,50,100);if(p.age<=25&&p.rating<p.potential&&r()<.025+(c.staffRating||65)/2500){p.rating++;const a=keyAttribute(p.position);p[a]=clamp(p[a]+1,25,99);p.value=playerValue(p.rating,p.age,p.potential);}}}}

export function getStaff(state,role){return state.staff.find(s=>s.role===role)||null;}
export function hireStaff(state,candidateId){const c=state.staffCandidates.find(x=>x.id===candidateId);if(!c)return{ok:false,message:'Candidate unavailable'};const fee=Math.max(.4,Math.round(c.wage*.035*10)/10);if(state.budget<fee)return{ok:false,message:'Not enough budget'};state.budget-=fee;state.clubs[state.clubId].budget=state.budget;state.staff=state.staff.filter(s=>s.role!==c.role);state.staff.push({...c,id:uid('staff')});state.staffCandidates=state.staffCandidates.filter(x=>x.id!==candidateId);state.inbox.push(`${c.name} joined as ${c.role}.`);return{ok:true,message:`Hired ${c.name}`};}

export function chooseSponsor(state,sponsorId){if(state.sponsor.active)return{ok:false,message:'Sponsor already selected'};const s=state.sponsor.offers.find(x=>x.id===sponsorId);if(!s)return{ok:false,message:'Sponsor unavailable'};state.sponsor.active={...s,progress:0};state.budget+=s.upfront;state.clubs[state.clubId].budget=state.budget;state.inbox.push(`${s.name} signed. €${s.upfront}m upfront.`);return{ok:true,message:`Signed ${s.name}`};}

export function draftPlayer(state,instanceId){if(!state.draft.open||state.draft.picksLeft<=0)return{ok:false,message:'Draft closed'};const idx=state.draft.pool.findIndex(p=>p.instanceId===instanceId);if(idx<0)return{ok:false,message:'Prospect unavailable'};const [p]=state.draft.pool.splice(idx,1);p.team=clubById(state.clubId).name;p.contract.years=4;p.contract.morale=82;state.squad.push(p);state.draft.picksLeft--;state.draft.round++;const r=seeded(`ai-draft-${state.season}-${state.draft.round}`);if(state.draft.pool.length>2){const aiPick=Math.floor(r()*state.draft.pool.length);state.draft.pool.splice(aiPick,1);}if(state.draft.picksLeft<=0)state.draft.open=false;state.inbox.push(`Drafted ${p.name}, ${p.position}, OVR ${p.rating}, potential ${p.potential}.`);return{ok:true,player:p};}
export function skipDraft(state){state.draft.open=false;state.inbox.push('You ended the draft early.');}

export function marketPlayers(state){const rows=[];for(const [clubId,c] of Object.entries(state.clubs)){if(clubId===state.clubId)continue;for(const p of c.squad)rows.push({...p,sellerId:clubId});}return rows;}
export function scoutPlayer(state,instanceId){const target=marketPlayers(state).find(p=>p.instanceId===instanceId);if(!target)return{ok:false,message:'Player not found'};if(state.scoutingPoints<1)return{ok:false,message:'No scouting points'};state.scoutingPoints--;const scout=getStaff(state,'Scout')?.rating||58;const spread=Math.max(1,Math.round((100-scout)/12));state.scoutReports[instanceId]={potentialLow:clamp(target.potential-spread,40,99),potentialHigh:clamp(target.potential+spread,40,99),valueLow:Math.round(target.value*.92*10)/10,valueHigh:Math.round(target.value*1.10*10)/10,week:state.week,season:state.season};return{ok:true,report:state.scoutReports[instanceId]};}
export function buyPlayer(state,instanceId,offerValue=null,wageOffer=null){const target=marketPlayers(state).find(p=>p.instanceId===instanceId);if(!target)return{ok:false,message:'Player no longer available'};const seller=state.clubs[target.sellerId];const recruiter=styleById(state.manager.style).bonus.negotiation||0;const price=offerValue==null?Math.round(target.value*1.08*10)/10:Number(offerValue);const wage=wageOffer==null?Math.round(target.contract.wage*1.12):Number(wageOffer);if(!Number.isFinite(price)||!Number.isFinite(wage)||price<=0||wage<=0)return{ok:false,message:'Invalid offer'};if(state.budget<price)return{ok:false,message:'Transfer budget too low'};const threshold=target.value*(target.listed?.88:1.02)*(1+clubById(target.sellerId).reputation/900);const playerNeed=target.contract.wage*(1.02+(target.rating-70)/300);const sellerAccept=price>=threshold*(1-recruiter/100);const playerAccept=wage>=playerNeed*(1-recruiter/130);if(!sellerAccept)return{ok:false,message:`Club rejected. They want around €${Math.round(threshold*10)/10}m.`};if(!playerAccept)return{ok:false,message:`Player rejected the contract. Expected about €${Math.round(playerNeed)}k/w.`};seller.squad=seller.squad.filter(p=>p.instanceId!==instanceId);const signed={...target,team:clubById(state.clubId).name,sellerId:undefined,listed:false,contract:{...target.contract,years:3,wage:Math.round(wage),morale:78}};state.squad.push(signed);state.budget-=price;state.clubs[state.clubId].budget=state.budget;state.manager.reputation=clamp(state.manager.reputation+Math.max(0,(signed.rating-75)*.08),0,100);state.inbox.push(`Signed ${signed.name} for €${price.toFixed(1)}m.`);return{ok:true,player:signed,price};}
export function toggleListPlayer(state,instanceId){const p=state.squad.find(x=>x.instanceId===instanceId);if(!p)return{ok:false,message:'Player not found'};p.listed=!p.listed;return{ok:true,listed:p.listed};}
export function renewContract(state,instanceId,years=3,wageOffer=null){const p=state.squad.find(x=>x.instanceId===instanceId);if(!p)return{ok:false,message:'Player not found'};const requested=Math.round(p.contract.wage*(1.08+Math.max(0,p.rating-78)/100));const offer=Number(wageOffer||requested);const moraleFactor=p.contract.morale<50?1.12:1;const accepted=offer>=requested*moraleFactor;if(!accepted)return{ok:false,message:`Rejected. Expected about €${Math.round(requested*moraleFactor)}k/w.`};p.contract.years=clamp(Number(years)||3,1,5);p.contract.wage=Math.round(offer);p.contract.morale=clamp(p.contract.morale+5,0,100);return{ok:true,message:`${p.name} renewed for ${p.contract.years} years.`};}

function generateIncomingOffers(state){const listed=state.squad.filter(p=>p.listed);const r=seeded(`offers-${state.clubId}-${state.season}-${state.week}`);const existing=new Set(state.incomingOffers.filter(o=>o.status==='pending').map(o=>o.playerId));for(const p of listed){if(existing.has(p.instanceId)||r()>.48)continue;const buyers=countryById(state.countryId).clubs.filter(c=>c.id!==state.clubId);const buyer=buyers[Math.floor(r()*buyers.length)];const amount=Math.round(p.value*(.85+r()*.35)*10)/10;state.incomingOffers.push({id:uid('offer',r),playerId:p.instanceId,buyerId:buyer.id,amount,status:'pending',week:state.week});}}
export function acceptIncomingOffer(state,offerId){const offer=state.incomingOffers.find(o=>o.id===offerId);if(!offer||offer.status!=='pending')return{ok:false,message:'Offer unavailable'};const p=state.squad.find(x=>x.instanceId===offer.playerId);if(!p)return{ok:false,message:'Player unavailable'};state.squad=state.squad.filter(x=>x.instanceId!==p.instanceId);state.clubs[state.clubId].squad=state.squad;p.team=clubById(offer.buyerId).name;p.listed=false;state.clubs[offer.buyerId].squad.push(p);state.budget+=offer.amount;state.clubs[state.clubId].budget=state.budget;offer.status='accepted';state.startingXI=state.startingXI.filter(id=>id!==p.instanceId);state.inbox.push(`Sold ${p.name} to ${p.team} for €${offer.amount.toFixed(1)}m.`);return{ok:true};}
export function rejectIncomingOffer(state,offerId){const offer=state.incomingOffers.find(o=>o.id===offerId);if(!offer||offer.status!=='pending')return{ok:false,message:'Offer unavailable'};offer.status='rejected';return{ok:true};}

export function updateTactics(state,patch){state.tactics={...state.tactics,...patch};state.clubs[state.clubId].tactics={...state.tactics};}
export function wageLoad(state){return state.squad.reduce((s,p)=>s+p.contract.wage,0)+state.staff.reduce((s,x)=>s+x.wage,0);}

export function simulateAIResult(state,fixture){const h=clubStrength(state,fixture.home),a=clubStrength(state,fixture.away);const r=seeded(`sim-${state.season}-${fixture.id}`);const hExp=clamp(1.15+(h-a)*.055+.18,.25,3.7),aExp=clamp(1.02+(a-h)*.055,.2,3.5);return[poisson(hExp,r),poisson(aExp,r)];}
function poisson(lambda,r){let L=Math.exp(-lambda),k=0,p=1;do{k++;p*=r();}while(p>L&&k<8);return k-1;}
function applyTableResult(state,homeId,awayId,homeGoals,awayGoals){const h=state.table.find(x=>x.clubId===homeId),a=state.table.find(x=>x.clubId===awayId);if(!h||!a)return;h.p++;a.p++;h.gf+=homeGoals;h.ga+=awayGoals;a.gf+=awayGoals;a.ga+=homeGoals;if(homeGoals>awayGoals){h.w++;a.l++;h.pts+=3;}else if(awayGoals>homeGoals){a.w++;h.l++;a.pts+=3;}else{h.d++;a.d++;h.pts++;a.pts++;}}

export function completeUserLeagueMatch(state,fixtureId,score,matchReport={}){const round=state.schedule.find(r=>r.fixtures.some(f=>f.id===fixtureId));const fixture=round?.fixtures.find(f=>f.id===fixtureId);if(!fixture||fixture.played)return{ok:false,message:'Fixture unavailable'};fixture.played=true;fixture.score=[Number(score[0])||0,Number(score[1])||0];applyTableResult(state,fixture.home,fixture.away,fixture.score[0],fixture.score[1]);const userHome=fixture.home===state.clubId;const gf=userHome?fixture.score[0]:fixture.score[1],ga=userHome?fixture.score[1]:fixture.score[0];updateManagerRecord(state,gf,ga);updatePlayerPostMatch(state,matchReport,gf,ga);state.lastResult={fixtureId,home:fixture.home,away:fixture.away,score:fixture.score,report:matchReport};simulateRestOfRound(state,round,fixtureId);progressCupIfDue(state);finalizeWeek(state);return{ok:true};}
function simulateRestOfRound(state,round,userFixtureId){for(const f of round.fixtures){if(f.id===userFixtureId||f.played)continue;const score=simulateAIResult(state,f);f.played=true;f.score=score;applyTableResult(state,f.home,f.away,score[0],score[1]);}}
function updateManagerRecord(state,gf,ga){const r=state.manager.record;r.gf+=gf;r.ga+=ga;if(gf>ga){r.w++;state.manager.reputation=clamp(state.manager.reputation+1.1,0,100);state.manager.board=clamp(state.manager.board+1.4,0,100);state.manager.dressingRoom=clamp(state.manager.dressingRoom+2,0,100);}else if(gf===ga){r.d++;state.manager.reputation=clamp(state.manager.reputation+.25,0,100);state.manager.board=clamp(state.manager.board+.2,0,100);}else{r.l++;state.manager.board=clamp(state.manager.board-2.2,0,100);state.manager.dressingRoom=clamp(state.manager.dressingRoom-1.5,0,100);}state.manager.tempMatchBonus=0;}
function updatePlayerPostMatch(state,report,gf,ga){const starters=selectedXI(state);const scorers=report.scorers||[];for(const p of starters){p.stats.apps++;p.contract.fitness=clamp(p.contract.fitness-(6+(state.tactics.tempo||55)*.045+(state.tactics.pressing||55)*.035),20,100);const goals=scorers.filter(x=>x===p.name).length;p.stats.goals+=goals;p.form=clamp(p.form+(gf>ga?1:gf<ga?-1:0)+(goals?1:0),-5,5);}for(const p of state.squad){if(p.injury)p.injury=Math.max(0,p.injury-1);if(p.suspended)p.suspended=Math.max(0,p.suspended-1);}}
function finalizeWeek(state){trainAIClubs(state);weeklyRecovery(state);aiMarketMove(state);generateIncomingOffers(state);if(state.sponsor.active){state.budget+=state.sponsor.active.weekly;state.clubs[state.clubId].budget=state.budget;updateSponsorProgress(state);}state.scoutingPoints=clamp(state.scoutingPoints+1,0,8);state.week++;state.trainingDoneWeek=null;state.eventResolved=false;state.currentEvent=state.week<=state.schedule.length?pickNarrativeEvent(state.clubId,state.season,state.week):null;if(state.week>state.schedule.length){finishSeason(state);}else{state.inbox.push(`Week ${state.week}: new decisions and match preparation are available.`);}}
function weeklyRecovery(state){const physio=getStaff(state,'Physio')?.rating||60;for(const p of state.squad){p.contract.fitness=clamp(p.contract.fitness+9+physio/14,25,100);p.contract.morale=clamp(p.contract.morale+(state.manager.dressingRoom-65)*.025,25,100);}}
function aiMarketMove(state){const r=seeded(`ai-market-${state.season}-${state.week}`);if(r()>.35)return;const clubIds=Object.keys(state.clubs).filter(id=>id!==state.clubId);const from=state.clubs[clubIds[Math.floor(r()*clubIds.length)]],to=state.clubs[clubIds[Math.floor(r()*clubIds.length)]];if(!from||!to||from===to)return;const candidate=[...from.squad].sort((a,b)=>a.rating-b.rating)[Math.floor(r()*Math.min(5,from.squad.length))];if(!candidate)return;from.squad=from.squad.filter(p=>p.instanceId!==candidate.instanceId);candidate.team=clubById(to.clubId).name;to.squad.push(candidate);state.worldLog.push(`${candidate.name} moved to ${candidate.team}.`);}

function progressCupIfDue(state){if(!state.cup||state.cup.champion)return;const week=state.week;const r=seeded(`cup-${state.season}-${week}`);if(week===3&&state.cup.stage==='Preliminary'){for(const f of state.cup.fixtures){const score=simulateCupFixture(state,f,r);f.played=true;f.score=score;}const winners=state.cup.fixtures.map(f=>f.score[0]>f.score[1]?f.home:f.away);const semiTeams=[...state.cup.byes,...winners];state.cup.semis=[{id:`cup-${state.season}-s1`,stage:'Semi-final',home:semiTeams[0],away:semiTeams[3],played:false},{id:`cup-${state.season}-s2`,stage:'Semi-final',home:semiTeams[1],away:semiTeams[2],played:false}];state.cup.stage='Semi-final';}
  else if(week===6&&state.cup.stage==='Semi-final'){for(const f of state.cup.semis){const score=simulateCupFixture(state,f,r);f.played=true;f.score=score;}const winners=state.cup.semis.map(f=>f.score[0]>f.score[1]?f.home:f.away);state.cup.final={id:`cup-${state.season}-final`,stage:'Final',home:winners[0],away:winners[1],played:false};state.cup.stage='Final';}
  else if(week===9&&state.cup.stage==='Final'&&state.cup.final){const score=simulateCupFixture(state,state.cup.final,r);state.cup.final.played=true;state.cup.final.score=score;state.cup.champion=score[0]>score[1]?state.cup.final.home:state.cup.final.away;state.cup.stage='Complete';if(state.cup.champion===state.clubId){state.manager.trophies.push({season:state.season,name:`${countryById(state.countryId).name} Cup`});state.manager.legacy+=12;state.manager.reputation=clamp(state.manager.reputation+6,0,100);state.inbox.push('You won the domestic cup.');}}}
function simulateCupFixture(state,f,r){let h=clubStrength(state,f.home),a=clubStrength(state,f.away);let hg=poisson(clamp(1.2+(h-a)*.05,.2,3.5),r),ag=poisson(clamp(1.05+(a-h)*.05,.2,3.4),r);if(hg===ag){if(r()<.5)hg++;else ag++;}return[hg,ag];}

function updateSponsorProgress(state){const s=state.sponsor.active;if(!s)return;const target=s.target.toLowerCase();if(target.includes('score 18'))s.progress=state.manager.record.gf;else if(target.includes('morale'))s.progress=state.manager.dressingRoom;else if(target.includes('top'))s.progress=leaguePosition(state);else if(target.includes('cup'))s.progress=state.cup.stage==='Final'||state.cup.champion===state.clubId?1:0;}
function sponsorTargetMet(state){const s=state.sponsor.active;if(!s)return false;const t=s.target.toLowerCase();if(t.includes('top half'))return leaguePosition(state)<=Math.ceil(state.table.length/2);if(t.includes('score 18'))return state.manager.record.gf>=18;if(t.includes('cup final'))return state.cup.final&&(state.cup.final.home===state.clubId||state.cup.final.away===state.clubId);if(t.includes('top 2'))return leaguePosition(state)<=2;if(t.includes('morale'))return state.manager.dressingRoom>=70;return false;}

function finishSeason(state){state.seasonComplete=true;state.manager.seasons++;const pos=leaguePosition(state);const champion=pos===1;if(champion){state.manager.trophies.push({season:state.season,name:countryById(state.countryId).league});state.manager.legacy+=20;state.manager.reputation=clamp(state.manager.reputation+9,0,100);}state.manager.legacy+=Math.max(1,state.table.length-pos+1);if(state.sponsor.active&&sponsorTargetMet(state)){state.budget+=state.sponsor.active.bonus;state.inbox.push(`Sponsor objective completed: +€${state.sponsor.active.bonus}m.`);}const prize=Math.max(4,(state.table.length-pos+1)*4);state.budget+=prize;state.clubs[state.clubId].budget=state.budget;state.inbox.push(`Season ${state.season} complete: position #${pos}, prize €${prize}m.`);state.jobOffers=generateJobOffers(state);}
function generateJobOffers(state){const currentRep=clubById(state.clubId).reputation;return countryById(state.countryId).clubs.filter(c=>c.id!==state.clubId&&c.reputation<=currentRep+12&&c.reputation>=currentRep-8).sort((a,b)=>b.reputation-a.reputation).slice(0,3).map(c=>({clubId:c.id,wage:Math.round(c.reputation*1.4),budgetBoost:Math.round(c.budget*.12)}));}
export function acceptJobOffer(state,clubId){if(!state.seasonComplete)return{ok:false,message:'Job changes happen after the season'};const offer=state.jobOffers.find(o=>o.clubId===clubId);if(!offer)return{ok:false,message:'Offer unavailable'};state.clubId=clubId;const club=clubById(clubId);state.budget=state.clubs[clubId].budget+offer.budgetBoost;state.clubs[clubId].budget=state.budget;state.wageBudget=state.clubs[clubId].wageBudget;state.staff=defaultUserStaff(club);state.tactics={...state.clubs[clubId].tactics};state.squad=state.clubs[clubId].squad;state.startingXI=autoPickXI(state).map(p=>p.instanceId);state.inbox.push(`You accepted the ${club.name} job.`);return{ok:true};}

export function startNextSeason(state){if(!state.seasonComplete)return{ok:false,message:'Season still active'};state.season++;state.week=1;state.seasonComplete=false;state.manager.record={w:0,d:0,l:0,gf:0,ga:0};for(const c of Object.values(state.clubs)){for(const p of c.squad){p.age++;p.contract.years--;p.stats={apps:0,goals:0,assists:0,yellow:0,red:0,avg:0};p.form=0;p.injury=0;p.contract.fitness=100;if(p.contract.years<=0){p.contract.years=1;p.contract.wage=Math.round(p.contract.wage*.92);p.contract.morale=clamp(p.contract.morale-8,25,100);}if(p.age>31&&p.rating>55&&seeded(`${p.instanceId}-${state.season}`)()<.4)p.rating--;p.value=playerValue(p.rating,p.age,p.potential);}}
  state.schedule=makeRoundRobin(state.countryId,state.season);state.table=initTable(state.countryId);state.cup=makeCup(state.countryId,state.season);state.draft={open:true,picksLeft:3,round:1,pool:makeDraftPool(state.countryId,state.season)};state.sponsor={active:null,offers:sponsorOffers(state.clubId,state.season)};state.staffCandidates=makeStaffCandidates(clubById(state.clubId),state.season);state.currentEvent=pickNarrativeEvent(state.clubId,state.season,1);state.eventResolved=false;state.trainingDoneWeek=null;state.incomingOffers=[];state.scoutingPoints=4;state.jobOffers=[];state.budget+=10;state.clubs[state.clubId].budget=state.budget;state.inbox.push(`Season ${state.season} begins. New sponsor, draft and league schedule are ready.`);return{ok:true};}

export function managerVerdict(state){const m=state.manager;const score=clamp(Math.round(m.legacy+m.reputation*.7+m.board*.25+m.trophies.length*8),0,180);if(score>=145)return{grade:'LEGEND',text:'A dynasty-level manager career.'};if(score>=115)return{grade:'ICON',text:'A career remembered by the club and league.'};if(score>=85)return{grade:'ELITE',text:'A high-level manager with major achievements.'};if(score>=60)return{grade:'RESPECTED',text:'A solid career with a clear football identity.'};return{grade:'PROVING GROUND',text:'The story is still being written.'};}

export function saveCareer(state){syncUserClub(state);localStorage.setItem(STORE_KEY,JSON.stringify(state));}
export function loadCareer(){try{const raw=JSON.parse(localStorage.getItem(STORE_KEY));if(!raw)return null;if(raw.version!==CAREER_VERSION)return migrateCareer(raw);syncUserClub(raw);return raw;}catch{return null;}}
export function clearCareer(){localStorage.removeItem(STORE_KEY);}
function migrateCareer(raw){if(!raw||!raw.clubId||!raw.countryId)return null;const fresh=createCareer({manager:raw.manager?.name||raw.manager||'Manager',nationality:raw.manager?.nationality||raw.countryId,style:raw.manager?.style||'tactician',countryId:raw.countryId,clubId:raw.clubId});fresh.inbox.push('A previous save was migrated to the new career engine.');return fresh;}
