const c=(id,name,country,color,prestige=78)=>({id,name,country,color,prestige,reputation:Math.round(76+(prestige-70)*.22)});

export const COUNTRIES=[
{id:'EN',name:'England',flag:'🇬🇧',league:'Premier League 2026/27',season:'2026/27',clubs:[c('arsenal','Arsenal','EN','#ef0107',92),c('aston-villa','Aston Villa','EN','#670e36',84),c('bournemouth','Bournemouth','EN','#da291c',78),c('brentford','Brentford','EN','#e30613',79),c('brighton','Brighton & Hove Albion','EN','#0057b8',81),c('chelsea','Chelsea','EN','#034694',88),c('coventry','Coventry City','EN','#66b3e3',72),c('crystal-palace','Crystal Palace','EN','#1b458f',80),c('everton','Everton','EN','#003399',79),c('fulham','Fulham','EN','#fff',79),c('hull','Hull City','EN','#f5a12b',71),c('ipswich','Ipswich Town','EN','#0044a7',73),c('leeds','Leeds United','EN','#fff',77),c('liverpool','Liverpool','EN','#c8102e',89),c('man-city','Manchester City','EN','#6cabdd',91),c('man-utd','Manchester United','EN','#da291c',85),c('newcastle','Newcastle United','EN','#111',84),c('nottingham-forest','Nottingham Forest','EN','#d00',82),c('sunderland','Sunderland','EN','#eb172b',75),c('tottenham','Tottenham Hotspur','EN','#132257',83)]},
{id:'ES',name:'Spain',flag:'🇪🇸',league:'LaLiga 2026/27',season:'2026/27',clubs:[c('athletic','Athletic Club','ES','#ee2523',84),c('atletico','Atlético de Madrid','ES','#d71920',88),c('osasuna','CA Osasuna','ES','#0a346f',78),c('celta','Celta','ES','#8ac7db',79),c('alaves','Deportivo Alavés','ES','#00529f',75),c('elche','Elche CF','ES','#007a33',74),c('barcelona','FC Barcelona','ES','#a50044',92),c('getafe','Getafe CF','ES','#005999',77),c('levante','Levante UD','ES','#0055a5',75),c('malaga','Málaga CF','ES','#6db4e4',73),c('racing','Racing Club','ES','#138c44',73),c('deportivo','RC Deportivo','ES','#1464a5',74),c('espanyol','RCD Espanyol','ES','#2f69bf',77),c('betis','Real Betis','ES','#159447',82),c('real-madrid','Real Madrid','ES','#f3f3f3',93),c('real-sociedad','Real Sociedad','ES','#1761a0',82),c('sevilla','Sevilla FC','ES','#d71920',79),c('valencia','Valencia CF','ES','#f5a623',79),c('villarreal','Villarreal CF','ES','#f3df20',83),c('rayo','Rayo Vallecano','ES','#fff',77)]},
{id:'IT',name:'Italy',flag:'🇮🇹',league:'Serie A 2026/27',season:'2026/27',clubs:[c('atalanta','Atalanta','IT','#1e71b8',85),c('bologna','Bologna','IT','#1b365d',82),c('cagliari','Cagliari','IT','#1b365d',75),c('como','Como','IT','#1764aa',83),c('fiorentina','Fiorentina','IT','#4b2e83',82),c('frosinone','Frosinone','IT','#f4d11a',73),c('genoa','Genoa','IT','#c8102e',77),c('inter','Inter','IT','#00529f',91),c('juventus','Juventus','IT','#fff',86),c('lazio','Lazio','IT','#87ceeb',81),c('lecce','Lecce','IT','#f4d019',74),c('milan','AC Milan','IT','#fb090b',87),c('monza','Monza','IT','#e30613',73),c('napoli','Napoli','IT','#12a0d7',88),c('parma','Parma','IT','#f5d90a',76),c('roma','Roma','IT','#8e1f2d',84),c('sassuolo','Sassuolo','IT','#179644',78),c('torino','Torino','IT','#7a263a',78),c('udinese','Udinese','IT','#111',77),c('venezia','Venezia','IT','#ff6b00',74)]},
{id:'DE',name:'Germany',flag:'🇩🇪',league:'Bundesliga 2026/27',season:'2026/27',clubs:[c('augsburg','FC Augsburg','DE','#ba3733',77),c('union-berlin','1. FC Union Berlin','DE','#e30613',77),c('werder','Werder Bremen','DE','#008557',79),c('dortmund','Borussia Dortmund','DE','#fde100',86),c('elversberg','SV Elversberg','DE','#111',71),c('frankfurt','Eintracht Frankfurt','DE','#e1000f',83),c('freiburg','SC Freiburg','DE','#d71920',81),c('hamburg','Hamburger SV','DE','#005aaa',75),c('hoffenheim','TSG Hoffenheim','DE','#1961b5',78),c('koln','1. FC Köln','DE','#fff',76),c('leipzig','RB Leipzig','DE','#dd0741',83),c('leverkusen','Bayer Leverkusen','DE','#e32221',88),c('mainz','1. FSV Mainz 05','DE','#c3142d',79),c('gladbach','Borussia Mönchengladbach','DE','#111',79),c('bayern','Bayern Munich','DE','#dc052d',92),c('paderborn','SC Paderborn 07','DE','#005ca9',71),c('schalke','FC Schalke 04','DE','#0063ad',75),c('stuttgart','VfB Stuttgart','DE','#e32221',82)]},
{id:'FR',name:'France',flag:'🇫🇷',league:'Ligue 1 2026/27',season:'2026/27',clubs:[c('angers','Angers SCO','FR','#111',74),c('auxerre','AJ Auxerre','FR','#1555a2',76),c('brest','Stade Brestois 29','FR','#d71920',78),c('le-havre','Le Havre AC','FR','#6aaad9',74),c('le-mans','Le Mans FC','FR','#d71920',72),c('lens','RC Lens','FR','#f6d313',84),c('lorient','FC Lorient','FR','#f58220',75),c('lille','LOSC Lille','FR','#d71920',83),c('lyon','Olympique Lyonnais','FR','#1f4a91',81),c('marseille','Olympique de Marseille','FR','#2faee0',85),c('monaco','AS Monaco','FR','#e51b23',84),c('nice','OGC Nice','FR','#c51b2f',80),c('paris-fc','Paris FC','FR','#1c3d75',76),c('psg','Paris Saint-Germain','FR','#004170',93),c('rennes','Stade Rennais','FR','#d71920',81),c('strasbourg','RC Strasbourg Alsace','FR','#1494ce',82),c('toulouse','Toulouse FC','FR','#654ea3',78),c('troyes','ESTAC Troyes','FR','#2879bd',73)]},
{id:'BR',name:'Brazil',flag:'🇧🇷',league:'Brasileirão Série A 2026',season:'2026',clubs:[c('athletico-pr','Athletico Paranaense','BR','#d71920',82),c('atletico-mg','Atlético Mineiro','BR','#111',84),c('bahia','Bahia','BR','#0057b8',81),c('botafogo','Botafogo','BR','#111',83),c('chapecoense','Chapecoense','BR','#008c45',72),c('corinthians','Corinthians','BR','#fff',84),c('coritiba','Coritiba','BR','#0d7b42',73),c('cruzeiro','Cruzeiro','BR','#0046ad',82),c('flamengo','Flamengo','BR','#c52613',89),c('fluminense','Fluminense','BR','#7d1f35',83),c('gremio','Grêmio','BR','#4aa3d8',80),c('internacional','Internacional','BR','#d71920',81),c('mirassol','Mirassol','BR','#f7d117',74),c('palmeiras','Palmeiras','BR','#006437',89),c('bragantino','Red Bull Bragantino','BR','#d71920',79),c('remo','Remo','BR','#173e76',71),c('santos','Santos FC','BR','#fff',79),c('sao-paulo','São Paulo','BR','#e31b23',82),c('vasco','Vasco da Gama','BR','#111',79),c('vitoria','Vitória','BR','#d71920',75)]},
{id:'PT',name:'Portugal',flag:'🇵🇹',league:'Liga Portugal 2026/27',season:'2026/27',clubs:[c('academico','Académico de Viseu','PT','#111',72),c('alverca','FC Alverca','PT','#d71920',72),c('arouca','FC Arouca','PT','#f5d019',76),c('benfica','SL Benfica','PT','#e83030',88),c('braga','SC Braga','PT','#d31826',83),c('casa-pia','Casa Pia AC','PT','#111',75),c('estoril','Estoril Praia','PT','#f3d30a',76),c('estrela','Estrela Amadora','PT','#2d7d46',73),c('famalicao','FC Famalicão','PT','#fff',78),c('gil-vicente','Gil Vicente FC','PT','#d71920',77),c('maritimo','Marítimo','PT','#008f4c',73),c('moreirense','Moreirense FC','PT','#3c9a52',76),c('nacional','CD Nacional','PT','#111',73),c('porto','FC Porto','PT','#0b4ea2',87),c('rio-ave','Rio Ave FC','PT','#159447',75),c('santa-clara','Santa Clara','PT','#d71920',75),c('sporting','Sporting CP','PT','#1f8f4e',89),c('vitoria-sc','Vitória SC','PT','#fff',78)]},
{id:'AR',name:'Argentina',flag:'🇦🇷',league:'Liga Profesional 2026',season:'2026',clubs:[c('aldosivi','Aldosivi','AR','#f0c419',72),c('argentinos','Argentinos Juniors','AR','#d71920',78),c('atletico-tucuman','Atlético Tucumán','AR','#6bb7e9',75),c('banfield','Banfield','AR','#0c7a44',74),c('barracas','Barracas Central','AR','#d71920',72),c('belgrano','Belgrano','AR','#63b8e8',77),c('boca','Boca Juniors','AR','#003b75',86),c('central-cordoba','Central Córdoba','AR','#111',74),c('defensa','Defensa y Justicia','AR','#f3d20b',77),c('riestra','Deportivo Riestra','AR','#111',71),c('estudiantes','Estudiantes','AR','#c51d32',81),c('estudiantes-rc','Estudiantes de Río Cuarto','AR','#6bb7e9',70),c('gimnasia-lp','Gimnasia LP','AR','#fff',75),c('gimnasia-mza','Gimnasia Mendoza','AR','#111',70),c('huracan','Huracán','AR','#fff',78),c('independiente','Independiente','AR','#d71920',80),c('independiente-rivadavia','Independiente Rivadavia','AR','#1e57a6',74),c('instituto','Instituto','AR','#d71920',75),c('lanus','Lanús','AR','#6b1e2b',79),c('newells','Newell’s','AR','#d71920',77),c('platense','Platense','AR','#6b4226',76),c('racing-ar','Racing Club','AR','#5bb8e8',82),c('river','River Plate','AR','#d71920',87),c('rosario-central','Rosario Central','AR','#f5c400',80),c('san-lorenzo','San Lorenzo','AR','#184a8b',78),c('sarmiento','Sarmiento','AR','#228b22',72),c('talleres','Talleres','AR','#1e4d8f',80),c('tigre','Tigre','AR','#1e4d8f',76),c('union','Unión','AR','#d71920',76),c('velez','Vélez Sarsfield','AR','#fff',80)]}
];

function rp(name,team,country,rating,position,age){const r=Math.min(78,rating),pace=position==='GK'?55:Math.min(86,r+2),shooting=['ST','LW','RW','CAM'].includes(position)?Math.min(87,r+3):Math.max(42,r-12),passing=['CM','CAM','CDM'].includes(position)?Math.min(88,r+3):r-2,dribbling=['LW','RW','CAM'].includes(position)?Math.min(88,r+4):r-2,defense=['CB','LB','RB','CDM','GK'].includes(position)?Math.min(88,r+4):Math.max(35,r-18),physical=['CB','CDM','ST','GK'].includes(position)?Math.min(88,r+3):r-3;return{id:`2026-${name}`,name,team,country,rating:r,position,pace,shooting,passing,dribbling,defense,physical,age,source:'football-elo-2026-mit'};}
export const SOURCE_PLAYERS=[rp('Rayan Aït-Nouri','Manchester City','Algeria',82,'LB',25),rp('Ramy Bensebaini','Borussia Dortmund','Algeria',80,'CB',31),rp('Ibrahim Maza','Bayer Leverkusen','Algeria',81,'CAM',20),rp('Farès Chaïbi','Eintracht Frankfurt','Algeria',78,'CM',23),rp('Aïssa Mandi','LOSC Lille','Algeria',76,'CB',34),rp('Amine Gouiri','Olympique de Marseille','Algeria',81,'ST',26),rp('Enzo Fernández','Chelsea','Argentina',87,'CM',25),rp('Alexis Mac Allister','Liverpool','Argentina',86,'CM',27),rp('Nico Paz','Como','Argentina',85,'CAM',21),rp('Cristian Romero','Tottenham Hotspur','Argentina',86,'CB',28),rp('Gonzalo Montiel','River Plate','Argentina',78,'RB',29),rp('Leandro Paredes','Boca Juniors','Argentina',80,'CDM',31),rp('Julián Álvarez','Atlético de Madrid','Argentina',90,'ST',26),rp('Lautaro Martínez','Inter','Argentina',89,'ST',28),rp('Giuliano Simeone','Atlético de Madrid','Argentina',82,'RW',23),rp('Nico González','Atlético de Madrid','Argentina',82,'LW',28),rp('Thiago Almada','Atlético de Madrid','Argentina',82,'CAM',25),rp('Mathew Ryan','Levante UD','Australia',75,'GK',34),rp('Alessandro Circati','Parma','Australia',76,'CB',22),rp('Cristian Volpato','Sassuolo','Australia',75,'CAM',22)];
const N=['Mateo Costa','Luca Silva','Nico Martin','Tomás Rossi','Leo Keller','Bruno Santos','Santi Morel','Iker Ferrer','Marco Pereira','Lucas García','Theo López','Rafa Mendes','João Romano','Noah Becker','Milo Rojas','Alex Navarro','Dani Duarte','Gabriel Schmidt','Julián Alves','Martín Torres','Enzo Vega','Pablo Molina','André Nunes','Victor Castro','Samuel Reyes','Hugo Campos','Felix Bianchi','Leon Pires','Max Suárez','Elias Meyer'];
export const OPEN_NAMES={EN:N,ES:N,IT:N,DE:N,FR:N,BR:N,PT:N,AR:N};
export const POSITIONS=[{id:'ST',name:'Delantero centro'},{id:'LW',name:'Extremo izquierdo'},{id:'RW',name:'Extremo derecho'},{id:'CAM',name:'Mediapunta'},{id:'CM',name:'Mediocampista'},{id:'CDM',name:'Mediocentro defensivo'},{id:'LB',name:'Lateral izquierdo'},{id:'RB',name:'Lateral derecho'},{id:'CB',name:'Defensor central'}];
export const BUILDS=[{id:'finisher',name:'Finisher',desc:'Ataque del área y definición.',mods:{shooting:8,composure:6,pace:2,passing:-2,defense:-4},tendencies:{shoot:1.35,dribble:.9,pass:.85}},{id:'creator',name:'Creator',desc:'Visión, pase final y juego entre líneas.',mods:{passing:8,vision:8,ballControl:4,shooting:-1,physical:-3},tendencies:{shoot:.8,dribble:1,pass:1.35}},{id:'technician',name:'Technician',desc:'Conducción, primer toque y 1v1.',mods:{dribbling:9,ballControl:8,pace:3,physical:-4,defense:-2},tendencies:{shoot:.9,dribble:1.5,pass:1}},{id:'engine',name:'Engine',desc:'Recorrido, presión y llegadas.',mods:{stamina:10,physical:5,pace:3,passing:3,shooting:-1},tendencies:{shoot:.9,dribble:.95,pass:1.1}},{id:'ball-winner',name:'Ball Winner',desc:'Anticipación, robo y duelos.',mods:{defense:9,physical:7,stamina:6,dribbling:-4,shooting:-4},tendencies:{shoot:.65,dribble:.7,pass:1.05}},{id:'speedster',name:'Speedster',desc:'Aceleración, ruptura y conducción larga.',mods:{pace:10,dribbling:5,stamina:3,passing:-3,physical:-2},tendencies:{shoot:1,dribble:1.35,pass:.85}},{id:'target',name:'Target Forward',desc:'Protección, fijación y remate.',mods:{physical:10,shooting:6,ballControl:4,pace:-5,dribbling:-2},tendencies:{shoot:1.25,dribble:.75,pass:.95}}];
export const SKILLS=[{id:'first-touch',name:'Primer toque',desc:'Controla mejor pases rápidos.',effects:{control:10}},{id:'quick-step',name:'Arranque explosivo',desc:'Aceleración extra tras superar un rival.',effects:{burst:10}},{id:'technical',name:'Técnico',desc:'Más éxito en cambios de dirección y regates.',effects:{dribble:10}},{id:'press-proof',name:'Press proof',desc:'Protege mejor la pelota bajo presión.',effects:{shield:10}},{id:'threaded-pass',name:'Pase filtrado',desc:'Mejor pase entre líneas.',effects:{pass:10}},{id:'finesse',name:'Tiro colocado',desc:'Más precisión cerca del área.',effects:{finesse:10}},{id:'power-shot',name:'Remate potente',desc:'Más velocidad en tiros largos.',effects:{shotPower:10}},{id:'interceptor',name:'Interceptor',desc:'Mayor radio y éxito de intercepción.',effects:{intercept:10}},{id:'relentless',name:'Incansable',desc:'Menor caída por stamina.',effects:{stamina:12}},{id:'aerial',name:'Dominio físico',desc:'Mejora cuerpo y protección.',effects:{physical:10}}];

let selectedRole='CM';
try{const saved=typeof localStorage!=='undefined'?JSON.parse(localStorage.getItem('career-eleven-2d:v4')||'null'):null;if(saved?.player?.position)selectedRole=saved.player.position;}catch{}
if(typeof document!=='undefined')document.addEventListener('change',e=>{if(e.target?.id==='position')selectedRole=e.target.value;});
const family=r=>['LB','CB','RB'].includes(r)?'DEF':['CDM','CM','CAM'].includes(r)?'MID':['LW','ST','RW'].includes(r)?'FWD':r;
function formation(name,pairs){const ordered=()=>{const fam=family(selectedRole);return [...pairs].sort((a,b)=>{const ar=a[0]===selectedRole?0:family(a[0])===fam?1:2,br=b[0]===selectedRole?0:family(b[0])===fam?1:2;return ar-br;});};return{name,get slots(){return ordered().map(x=>x[0]);},get anchors(){return ordered().map(x=>x[1]);}};}
export const FORMATIONS={
'4-3-3':formation('4-3-3',[['GK',[.06,.50]],['LB',[.22,.16]],['CB',[.19,.38]],['CB',[.19,.62]],['RB',[.22,.84]],['CDM',[.37,.50]],['CM',[.45,.32]],['CAM',[.53,.55]],['LW',[.69,.18]],['ST',[.74,.50]],['RW',[.69,.82]]]),
'4-2-3-1':formation('4-2-3-1',[['GK',[.06,.50]],['LB',[.22,.16]],['CB',[.19,.38]],['CB',[.19,.62]],['RB',[.22,.84]],['CDM',[.36,.42]],['CM',[.44,.62]],['CAM',[.56,.50]],['LW',[.59,.18]],['ST',[.75,.50]],['RW',[.59,.82]]]),
'4-4-2':formation('4-4-2 hybrid',[['GK',[.06,.50]],['LB',[.22,.16]],['CB',[.19,.38]],['CB',[.19,.62]],['RB',[.22,.84]],['CDM',[.39,.43]],['CM',[.45,.62]],['CAM',[.50,.34]],['LW',[.62,.16]],['ST',[.72,.47]],['RW',[.64,.82]]])};
export const USER_ROLE_ANCHORS={ST:[.74,.50],LW:[.68,.18],RW:[.68,.82],CAM:[.56,.50],CM:[.44,.50],CDM:[.36,.50],LB:[.22,.16],RB:[.22,.84],CB:[.20,.50]};
export const ATTRIBUTE_INFO={pace:'Aceleración y velocidad máxima.',shooting:'Precisión, potencia y definición.',passing:'Precisión y peso de pase.',dribbling:'Frecuencia, distancia y éxito de los toques de conducción.',defense:'Robos, anticipación e intercepciones.',physical:'Cuerpo, equilibrio y protección.',ballControl:'Primer toque y tamaño del toque al conducir.',vision:'Elección de receptor y lectura de espacios.',stamina:'Cuánto mantiene sus capacidades durante 90 minutos.',composure:'Error técnico bajo presión y al definir.'};
export const ROSTER_SYNC={url:'https://raw.githubusercontent.com/ericsanmiguel/football_elo/main/data/squads/2026.csv',repo:'ericsanmiguel/football_elo',license:'MIT',season:'2026',note:'Relaciones jugador-club 2026. Career Eleven deriva ratings de juego; no copia ratings propietarios.'};
export const DATA_SOURCES=[{name:'football_elo 2026 squads',repo:'ericsanmiguel/football_elo',license:'MIT',usage:'Relaciones jugador-club 2026 verificadas para refrescar el seed de planteles.'},{name:'openfootball/players',repo:'openfootball/players',license:'CC0-1.0 / public domain',usage:'Referencia de nombres/posiciones y fillers claramente generados.'},{name:'League official club lists',repo:'Fuentes oficiales de cada liga',license:'reference only',usage:'Participantes 2026/27 o 2026; sin assets.'}];
