const FIELD={left:60,right:900,top:55,bottom:505,goalTop:225,goalBottom:335};
const HAXBALL={playerRadius:12,ballRadius:7,playerDamping:.96,ballDamping:.99,playerBounce:.5,ballBounce:.5,acceleration:.12,kickStrength:5};
export class MatchEngine{
  constructor(home,away,options={}){this.homeName=options.homeName||'Home';this.awayName=options.awayName||'Away';this.seed=hashString(options.seed||`${this.homeName}-${this.awayName}`);this.rng=mulberry32(this.seed);this.score=[0,0];this.minute=0;this.finished=false;this.events=[];this.stats={shots:[0,0],touches:[0,0],possessionTicks:[0,0]};this.players=[];this.ball={x:480,y:280,vx:0,vy:0,r:HAXBALL.ballRadius,lastTeam:null,lastPlayer:null};this.makeTeam(home,0);this.makeTeam(away,1);this.resetPositions();}
  makeTeam(lineup,team){const slots=team===0?[[112,280],[245,280],[365,190],[365,370],[460,280]]:[[848,280],[715,280],[595,190],[595,370],[500,280]];lineup.slice(0,5).forEach((data,i)=>this.players.push({data,team,slot:i,x:slots[i][0],y:slots[i][1],homeX:slots[i][0],homeY:slots[i][1],vx:0,vy:0,r:HAXBALL.playerRadius,kickCooldown:0,fatigue:0}));}
  resetPositions(scoringTeam=null){const a=[[112,280],[245,280],[365,190],[365,370],[460,280]],b=[[848,280],[715,280],[595,190],[595,370],[500,280]];this.players.forEach(p=>{const pos=p.team===0?a[p.slot]:b[p.slot];p.x=pos[0];p.y=pos[1];p.homeX=pos[0];p.homeY=pos[1];p.vx=0;p.vy=0;p.kickCooldown=0});this.ball.x=480;this.ball.y=280;this.ball.vx=0;this.ball.vy=0;if(scoringTeam!==null)this.ball.x+=scoringTeam===0?-12:12;}
  step(dt){if(this.finished)return;dt=Math.min(dt,.05);this.minute+=dt;if(this.minute>=90){this.minute=90;this.finished=true;this.events.unshift({minute:90,text:'Full time'});return}const scale=dt*60;this.players.forEach(p=>this.updatePlayer(p,scale));this.players.forEach(p=>this.resolvePlayerBoundary(p));this.resolvePlayerCollisions();this.updateBall(scale);this.resolveBallPlayerCollisions();this.checkGoal();const poss=this.closestPlayer();if(poss&&dist(poss,this.ball)<42)this.stats.possessionTicks[poss.team]++;}
  updatePlayer(p,scale){if(p.kickCooldown>0)p.kickCooldown-=scale;const target=this.aiTarget(p),dx=target.x-p.x,dy=target.y-p.y,len=Math.hypot(dx,dy)||1,pace=p.data.pace??p.data.speed??70,fitnessPenalty=1-Math.min(.16,p.fatigue*.0015),accel=HAXBALL.acceleration*(.72+pace/135)*fitnessPenalty;p.vx+=(dx/len)*accel*scale;p.vy+=(dy/len)*accel*scale;const damp=Math.pow(HAXBALL.playerDamping,scale);p.vx*=damp;p.vy*=damp;const max=3+pace/100*1.55,speed=Math.hypot(p.vx,p.vy);if(speed>max){p.vx=p.vx/speed*max;p.vy=p.vy/speed*max}p.x+=p.vx*scale;p.y+=p.vy*scale;p.fatigue+=.0025*scale;this.tryKick(p);}
  aiTarget(p){const attackDir=p.team===0?1:-1,ball=this.ball,teammates=this.players.filter(x=>x.team===p.team),nearest=teammates.reduce((best,x)=>dist(x,ball)<dist(best,ball)?x:best,teammates[0]),losing=this.score[p.team]<this.score[1-p.team],urgency=losing&&this.minute>65?55:0;if(p.slot===0){const ownX=p.team===0?105:855,danger=p.team===0?ball.x<300:ball.x>660;return danger?{x:clamp(ball.x,p.team===0?80:760,p.team===0?250:880),y:clamp(ball.y,185,375)}:{x:ownX,y:clamp(ball.y,235,325)}}if(p===nearest)return{x:ball.x,y:ball.y};const flow=(ball.x-480)*.24+attackDir*urgency,baseX=p.homeX+flow,laneBias=p.slot===2?-85:p.slot===3?85:0,y=clamp(p.homeY+(ball.y-280)*.30+laneBias*.12,85,475);return{x:clamp(baseX,95,865),y};}
  tryKick(p){const d=dist(p,this.ball);if(d>p.r+this.ball.r+7||p.kickCooldown>0)return;p.kickCooldown=20;this.stats.touches[p.team]++;this.ball.lastTeam=p.team;this.ball.lastPlayer=p.data.name;const attackDir=p.team===0?1:-1,goalX=p.team===0?FIELD.right+32:FIELD.left-32,shooting=p.data.shooting??70,passing=p.data.passing??70,dribbling=p.data.dribbling??70,xProgress=p.team===0?p.x/FIELD.right:(FIELD.right-p.x)/FIELD.right,close=xProgress>.68,shouldShoot=close||this.rng()<.22+shooting/250;let tx=goalX,ty=280;if(!shouldShoot){const mates=this.players.filter(x=>x.team===p.team&&x!==p&&(p.team===0?x.x>p.x-30:x.x<p.x+30));if(mates.length){mates.sort((a,b)=>Math.abs(a.y-p.y)-Math.abs(b.y-p.y));const mate=mates[Math.floor(this.rng()*Math.min(2,mates.length))];tx=mate.x;ty=mate.y}else{tx=p.x+attackDir*140;ty=280}}else{this.stats.shots[p.team]++;const error=(100-shooting)/100*95;ty=280+(this.rng()-.5)*error}const dx=tx-this.ball.x,dy=ty-this.ball.y,len=Math.hypot(dx,dy)||1,skill=shouldShoot?shooting:passing,power=HAXBALL.kickStrength*(.78+skill/190)*(.93+dribbling/1000);this.ball.vx=dx/len*power+p.vx*.25;this.ball.vy=dy/len*power+p.vy*.25;}
  updateBall(scale){const damp=Math.pow(HAXBALL.ballDamping,scale);this.ball.vx*=damp;this.ball.vy*=damp;this.ball.x+=this.ball.vx*scale;this.ball.y+=this.ball.vy*scale;if(this.ball.y-this.ball.r<FIELD.top){this.ball.y=FIELD.top+this.ball.r;this.ball.vy=Math.abs(this.ball.vy)*HAXBALL.ballBounce}if(this.ball.y+this.ball.r>FIELD.bottom){this.ball.y=FIELD.bottom-this.ball.r;this.ball.vy=-Math.abs(this.ball.vy)*HAXBALL.ballBounce}const inGoalMouth=this.ball.y>FIELD.goalTop&&this.ball.y<FIELD.goalBottom;if(!inGoalMouth&&this.ball.x-this.ball.r<FIELD.left){this.ball.x=FIELD.left+this.ball.r;this.ball.vx=Math.abs(this.ball.vx)*HAXBALL.ballBounce}if(!inGoalMouth&&this.ball.x+this.ball.r>FIELD.right){this.ball.x=FIELD.right-this.ball.r;this.ball.vx=-Math.abs(this.ball.vx)*HAXBALL.ballBounce}if(inGoalMouth){if(this.ball.x<FIELD.left-42){this.ball.x=FIELD.left-42;this.ball.vx=Math.abs(this.ball.vx)*.5}if(this.ball.x>FIELD.right+42){this.ball.x=FIELD.right+42;this.ball.vx=-Math.abs(this.ball.vx)*.5}}}
  resolvePlayerBoundary(p){p.x=clamp(p.x,FIELD.left+p.r,FIELD.right-p.r);p.y=clamp(p.y,FIELD.top+p.r,FIELD.bottom-p.r);}
  resolvePlayerCollisions(){for(let i=0;i<this.players.length;i++)for(let j=i+1;j<this.players.length;j++){const a=this.players[i],b=this.players[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=a.r+b.r;if(d<min){const nx=dx/d,ny=dy/d,overlap=(min-d)/2;a.x-=nx*overlap;a.y-=ny*overlap;b.x+=nx*overlap;b.y+=ny*overlap;const rvx=b.vx-a.vx,rvy=b.vy-a.vy,sep=rvx*nx+rvy*ny;if(sep<0){const impulse=-sep*(1+HAXBALL.playerBounce)*.5;a.vx-=impulse*nx;b.vx+=impulse*nx;a.vy-=impulse*ny;b.vy+=impulse*ny}}}}
  resolveBallPlayerCollisions(){this.players.forEach(p=>{const dx=this.ball.x-p.x,dy=this.ball.y-p.y,d=Math.hypot(dx,dy)||.01,min=this.ball.r+p.r;if(d<min){const nx=dx/d,ny=dy/d,over=min-d;this.ball.x+=nx*over;this.ball.y+=ny*over;const rel=(this.ball.vx-p.vx)*nx+(this.ball.vy-p.vy)*ny;if(rel<0){const impulse=-rel*(1+HAXBALL.ballBounce);this.ball.vx+=impulse*nx;this.ball.vy+=impulse*ny}this.ball.lastTeam=p.team;this.ball.lastPlayer=p.data.name}});}
  checkGoal(){if(this.ball.y<FIELD.goalTop||this.ball.y>FIELD.goalBottom)return;let scoring=null;if(this.ball.x<FIELD.left-12)scoring=1;if(this.ball.x>FIELD.right+12)scoring=0;if(scoring===null)return;this.score[scoring]++;const scorer=this.ball.lastTeam===scoring?this.ball.lastPlayer:'Own goal';this.events.unshift({minute:Math.max(1,Math.round(this.minute)),text:`GOAL — ${scorer}`,team:scoring});this.resetPositions(scoring);}
  closestPlayer(){return this.players.reduce((best,p)=>!best||dist(p,this.ball)<dist(best,this.ball)?p:best,null)}
  draw(ctx,width=960,height=560){ctx.clearRect(0,0,width,height);ctx.fillStyle='#163f2a';ctx.fillRect(0,0,width,height);ctx.fillStyle='#1d5b38';ctx.fillRect(FIELD.left,FIELD.top,FIELD.right-FIELD.left,FIELD.bottom-FIELD.top);ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=2;ctx.strokeRect(FIELD.left,FIELD.top,FIELD.right-FIELD.left,FIELD.bottom-FIELD.top);ctx.beginPath();ctx.moveTo(480,FIELD.top);ctx.lineTo(480,FIELD.bottom);ctx.stroke();ctx.beginPath();ctx.arc(480,280,72,0,Math.PI*2);ctx.stroke();ctx.strokeRect(FIELD.left-42,FIELD.goalTop,42,FIELD.goalBottom-FIELD.goalTop);ctx.strokeRect(FIELD.right,FIELD.goalTop,42,FIELD.goalBottom-FIELD.goalTop);ctx.strokeRect(FIELD.left,175,120,210);ctx.strokeRect(FIELD.right-120,175,120,210);this.players.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=p.team===0?'#e14646':'#4d82ff';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='600 9px system-ui';ctx.textAlign='center';ctx.fillText(shortName(p.data.name),p.x,p.y-17)});ctx.beginPath();ctx.arc(this.ball.x,this.ball.y,this.ball.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#111';ctx.lineWidth=1.5;ctx.stroke();}
}
function shortName(name){const parts=name.split(' ');return parts[parts.length-1].slice(0,11)}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function clamp(v,min,max){return Math.max(min,Math.min(max,v))}function hashString(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
