const CSS=`
:root{--bg:#101820!important;--panel:#18232c!important;--panel2:#202d36!important;--line:#6f7d86!important;--text:#f1ecdf!important;--muted:#bdc5c8!important;--lime:#75aadb!important;--gold:#d2ae6d!important;--red:#a93d3d!important;--violet:#75aadb!important;--shadow:none!important}
html,body{background:#111a21!important;color:#f1ecdf!important;font-family:"Arial Narrow","Bahnschrift Condensed","Roboto Condensed",Arial,sans-serif!important}body:before{background:repeating-linear-gradient(0deg,rgba(255,255,255,.018) 0,rgba(255,255,255,.018) 1px,transparent 1px,transparent 5px)!important;opacity:1!important}
.top{background:#0d1820!important;border-bottom:3px solid #75aadb!important;box-shadow:none!important}.top:after{color:#d2ae6d!important}.logo b,.eyebrow,.text,.overall,.live-rating b,.events b,.meaning b{color:#75aadb!important}.head span,.muted,small{color:#bdc5c8}
.card,.setup-card,.pc-card,.pc-stage,.pc-offer,.pc-overall,.training-live-status,.training-feedback,.training-commentary{background:#18232c!important;border:1px solid #56646d!important;border-radius:3px!important;box-shadow:none!important}.card:before,.setup-card:before{display:none!important}
.btn,.pc-btn,.training-live-actions button,.speed,.arg-nav-toggle{border-radius:2px!important;box-shadow:none!important;text-transform:uppercase;letter-spacing:.045em}.btn,.pc-btn,.training-live-actions .back{background:#75aadb!important;color:#0b1720!important;border:1px solid #9ac6e5!important}.btn.ghost,.training-live-actions .cancel,.speed{background:#202d36!important;color:#f1ecdf!important;border:1px solid #67747c!important}.speed.on,.nav-btn.on{background:#273a48!important;color:#f1ecdf!important;box-shadow:inset 4px 0 #75aadb!important}
.choice,.skill,.mini-stats span,.season-grid span,.xi>div,.plan span,.metric{background:#151f27!important;border-radius:2px!important}.choice:hover,.choice.selected,.skill.equipped,.xi .user{border-color:#75aadb!important}
.pill,.pc-pill,.session-pill,.training-engine-pill{display:inline-block!important;border:0!important;border-left:4px solid #75aadb!important;border-radius:0!important;background:transparent!important;color:#f1ecdf!important;padding:2px 7px!important;font-size:11px!important;font-weight:900!important;letter-spacing:.07em!important;text-transform:uppercase!important;line-height:1.3!important}.hero h1 span,body.match-live-active .hero h1 span{border-radius:1px!important;background:#0c171f!important;border:1px solid #7e8a91!important;border-left:5px solid #75aadb!important;color:#f1ecdf!important;padding:3px 8px!important}
.bar,.xpbar,.training-live-progress,.pc-stagebar{background:#0c151b!important;border-color:#56646d!important;border-radius:1px!important}.bar i,.xpbar i,.training-live-progress i,.pc-stagebar i{background:#75aadb!important;border-radius:0!important}.pc-head h1 span,.pc-overall b,.pc-progress .done,.pc-growth b,.pc-offer .interest{color:#75aadb!important}.pc-progress .done,.pc-card.done{border-color:#75aadb!important}.training-live-status.done{border-color:#75aadb!important}.training-feedback b,.training-commentary b{color:#d2ae6d!important}input[type="range"]{accent-color:#75aadb!important}
.training-sim-head{grid-area:head;display:flex!important;align-items:flex-start;justify-content:space-between;gap:12px;border-bottom:2px solid #56646d;padding-bottom:7px}.training-sim-head h1{font-size:clamp(24px,3.1vw,40px)!important;margin:2px 0!important;line-height:.95}.training-sim-head p{margin:4px 0 5px!important;max-width:760px;color:#bdc5c8!important}.training-sim-head .session-pill{white-space:nowrap}
#training-sim-shell[data-live-training="1"]{display:grid!important;grid-template-columns:minmax(0,1fr) 300px;grid-template-areas:"head head" "progress meta" "stage report" "stage status" "stage comments" "stage feedback" "stage actions";grid-template-rows:auto auto minmax(0,1fr) auto auto auto auto;gap:7px 10px;max-width:none!important;width:100%!important;height:calc(100dvh - 92px);overflow:hidden;padding:0!important}.training-live-progress{grid-area:progress;margin:0!important;height:8px!important;align-self:center}.training-live-meta{grid-area:meta;margin:0!important;display:block!important;font-size:11px!important;line-height:1.2!important}.training-live-meta span{display:block}.training-stage{grid-area:stage;min-width:0;min-height:0;display:flex!important;align-items:center;justify-content:center;overflow:hidden!important;border:1px solid #56646d;background:#0b151a}.training-stage canvas{display:block!important;width:auto!important;max-width:100%!important;height:auto!important;max-height:100%!important;aspect-ratio:11/7;margin:auto!important;border-radius:0!important}.training-report{grid-area:report!important;display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:5px!important;margin:0!important;align-self:start}.training-report>div{background:#111a21!important;border:1px solid #56646d!important;border-radius:1px!important;padding:7px!important}.training-report span{font-size:9px!important;letter-spacing:.07em}.training-report b{font-size:20px!important}.training-live-status{grid-area:status!important;margin:0!important;padding:8px 9px!important;min-height:0!important;max-height:58px;overflow:auto;font-size:12px;line-height:1.25}.training-commentary{grid-area:comments!important;margin:0!important;padding:7px 9px!important;min-height:0;max-height:110px;overflow:auto}.training-commentary>div:first-child{font-size:9px;font-weight:900;letter-spacing:.09em;color:#d2ae6d;margin-bottom:3px}.training-commentary p{margin:2px 0!important;padding-left:8px;border-left:2px solid #56646d;color:#d7dde0;font-size:10px;line-height:1.18}.training-commentary p:last-child{border-left-color:#75aadb;color:#f1ecdf}.training-feedback{grid-area:feedback!important;margin:0!important;padding:8px 9px!important;min-height:0;max-height:100px;overflow:auto}.training-feedback p{font-size:11px!important;line-height:1.25!important;margin:3px 0!important}.training-live-actions{grid-area:actions!important;margin:0!important;align-self:end}.training-live-actions button{width:100%;padding:8px 10px!important}
body.match-live-active .hero{background:#0d1820f5!important;border-radius:2px!important;border-color:#56646d!important}body.match-live-active .live-layout{gap:8px!important}.hud{border-radius:2px!important}.events{font-family:"Arial Narrow","Bahnschrift Condensed",Arial,sans-serif}.event{border-radius:0!important}
.pc-shell{background:#111a21!important}.pc-growth{background:#121c23!important;border-radius:2px!important}.pc-back{border-radius:2px!important}.pc-progress div{border-radius:1px!important;background:#121c23!important}
@media(max-width:980px){#training-sim-shell[data-live-training="1"]{grid-template-columns:minmax(0,1fr) 235px;height:calc(100dvh - 78px)}.training-sim-head p{display:none}.training-report b{font-size:17px!important}.training-live-status{max-height:48px}.training-commentary{max-height:78px}.training-feedback{max-height:70px}}
@media(max-width:720px){#training-sim-shell[data-live-training="1"]{display:grid!important;grid-template-columns:1fr!important;grid-template-areas:"head" "report" "stage" "status" "comments" "actions"!important;grid-template-rows:auto auto minmax(0,1fr) auto auto auto;height:calc(100dvh - 60px);gap:5px}.training-sim-head{display:block!important}.training-sim-head .training-engine-pill,.training-sim-head p,.training-live-progress,.training-live-meta,.training-feedback:not(.on){display:none!important}.training-sim-head h1{font-size:23px!important}.training-report{grid-template-columns:repeat(4,minmax(0,1fr))!important}.training-report>div{padding:4px!important}.training-report b{font-size:15px!important}.training-stage{min-height:0}.training-live-status{max-height:38px;font-size:10px}.training-commentary{max-height:48px}.training-commentary p{font-size:9px}.training-live-actions button{padding:6px!important}.card,.setup-card,.pc-card,.pc-stage,.pc-offer{border-radius:2px!important}}
`;

let lastTrainingStatus='';
function install(){if(document.querySelector('style[data-potrero-ui-v2]'))return;const style=document.createElement('style');style.dataset.potreroUiV2='1';style.textContent=CSS;document.head.appendChild(style);}
function trainingCommentary(){const shell=document.querySelector('#training-sim-shell[data-live-training="1"]'),status=document.querySelector('#trainingLiveStatus');if(!shell||!status){lastTrainingStatus='';return;}let panel=shell.querySelector('#trainingCommentary');if(!panel){panel=document.createElement('div');panel.id='trainingCommentary';panel.className='training-commentary';panel.innerHTML='<div>RELATO DEL ENTRENAMIENTO</div><section></section>';shell.appendChild(panel);}const text=(status.textContent||'').trim();if(!text||text===lastTrainingStatus)return;lastTrainingStatus=text;const log=panel.querySelector('section'),p=document.createElement('p');p.textContent=text;log.appendChild(p);while(log.children.length>6)log.firstElementChild.remove();panel.scrollTop=panel.scrollHeight;}
function decorate(){install();document.body.classList.toggle('training-live-active',!!document.querySelector('#training-sim-shell[data-live-training="1"]'));for(const el of document.querySelectorAll('.training-engine-pill'))if(/MISMO MOTOR/i.test(el.textContent||''))el.textContent='FÚTBOL REAL · MISMA FÍSICA DEL PARTIDO';trainingCommentary();}
new MutationObserver(decorate).observe(document.querySelector('#app')||document.body,{childList:true,subtree:true,characterData:true});decorate();

export const __potreroUiV2={decorate,trainingCommentary};
