import test from 'node:test';
import assert from 'node:assert/strict';
import {createPreCareerState,recordPreCareerDrill,recordTrialMatch} from '../precareer-v1.js';
import {acceptPreCareerOffer,generatePreCareerOffers,positionCompetition,projectedSquadRole} from '../precareer-offers-v1.js';

function prospect(overall=58){return{instanceId:'user-player',name:'Prospecto',position:'RW',age:17,rating:overall,country:'Argentina'};}
function scores(value){return{technical:value,tactical:value,physical:value,mentality:value};}
function readyState(value=70,overall=58){let state=createPreCareerState({player:prospect(overall),seed:'offer-seed'});for(const id of ['control','passing','finishing'])state=recordPreCareerDrill(state,{drillId:id,scores:scores(value)});state=recordTrialMatch(state,{matchId:'trial-1',scores:scores(value),minutes:75});state=recordTrialMatch(state,{matchId:'trial-2',scores:scores(value),minutes:90});return state;}
function club(id,reputation=78,roster=[]){return{id,name:id.toUpperCase(),country:'AR',countryId:'AR',league:'Liga de prueba',reputation,roster};}

test('offers cannot exist before drills and trial matches are complete',()=>{const state=createPreCareerState({player:prospect(),seed:'early'});assert.throws(()=>generatePreCareerOffers(state,{clubs:[club('a')]}),/assessment must be complete/);});

test('offer generation is deterministic and includes contract plus sporting pathway',()=>{const state=readyState(72);const clubs=[club('big',86),club('mid',79),club('small',72),club('other',76)];const a=generatePreCareerOffers(state,{clubs,count:4,minInterest:0}),b=generatePreCareerOffers(state,{clubs,count:4,minInterest:0});assert.deepEqual(a.offers,b.offers);assert.equal(a.status,'offers-received');assert.equal(a.stage,'awaiting-offers');for(const offer of a.offers){assert.ok(offer.contract.years>=2&&offer.contract.years<=4);assert.ok(offer.contract.weeklyWageUsd>=50);assert.ok(['reserve','development','rotation','first-team-competition'].includes(offer.projectedRole));assert.equal(offer.contract.squadRole,offer.projectedRole);assert.ok(offer.scoutingFit.confidence>0);}});

test('real positional shortage increases club interest and projected competition is exposed',()=>{const state=readyState(68);const crowded=club('crowded',78,[{position:'RW',rating:70},{position:'RW',rating:66},{position:'RW',rating:63},{position:'ST',rating:67}]);const open=club('open',78,[{position:'CM',rating:70},{position:'CB',rating:68}]);const next=generatePreCareerOffers(state,{clubs:[crowded,open],count:2,minInterest:0});const openOffer=next.offers.find(x=>x.clubId==='open'),crowdedOffer=next.offers.find(x=>x.clubId==='crowded');assert.ok(openOffer.interest>crowdedOffer.interest);assert.equal(openOffer.competition.exactPositionCount,0);assert.equal(crowdedOffer.competition.exactPositionCount,3);assert.ok(crowdedOffer.competition.projectedRank>=2);});

test('stronger trial evidence changes the sporting level of the same prospect',()=>{const target=club('target',78);const raw=generatePreCareerOffers(readyState(48,56),{clubs:[target],count:1,minInterest:0}).offers[0];const standout=generatePreCareerOffers(readyState(88,56),{clubs:[target],count:1,minInterest:0}).offers[0];assert.ok(standout.interest>raw.interest);const order=['reserve','development','rotation','first-team-competition'];assert.ok(order.indexOf(standout.projectedRole)>order.indexOf(raw.projectedRole));});

test('position competition uses roster ratings when available and a reputation baseline otherwise',()=>{const withRoster=positionCompetition(club('r',80,[{position:'RW',rating:67},{position:'RW',rating:62}]),'RW',65);assert.equal(withRoster.referenceOverall,64.5);assert.equal(withRoster.projectedRank,2);const withoutRoster=positionCompetition(club('n',80),'RW',65);assert.equal(withoutRoster.referenceOverall,68);assert.equal(projectedSquadRole({candidateOverall:69,club:club('n',80),competition:withoutRoster}),'rotation');});

test('accepting an offer signs the prospect without mutating the previous state',()=>{const offered=generatePreCareerOffers(readyState(74),{clubs:[club('a',75),club('b',82)],count:2,minInterest:0}),before=structuredClone(offered),chosen=offered.offers[0];const signed=acceptPreCareerOffer(offered,chosen.id);assert.deepEqual(offered,before);assert.equal(signed.signed,true);assert.equal(signed.status,'signed');assert.equal(signed.stage,'signed');assert.equal(signed.clubId,chosen.clubId);assert.equal(signed.countryId,chosen.countryId);assert.deepEqual(signed.contract,chosen.contract);assert.deepEqual(signed.selectedOffer,chosen);assert.throws(()=>acceptPreCareerOffer(signed,chosen.id),/already signed/);});
