import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {getWeeklyInteraction,resolveInteraction,weeklyDecisionGate} from '../campaign-events-v1.js';
import {adjustRelationship,applyLatestMatchChemistry,relationshipValue,syncCareerChemistryState,teamHierarchySnapshot} from '../team-chemistry-v1.js';
import {armChemistryPass,chemistryAdjustedPassOptions} from '../chemistry-decision-v1.js';
import {MatchEngine} from '../engine.js';

const player=(id,name,rating,position='CM',extra={})=>({id,instanceId:id,name,rating,position,age:24,pace:72,shooting:68,passing:74,dribbling:72,defense:62,physical:68,ballControl:75,vision:76,stamina:75,composure:74,fitness:100,form:0,potential:rating+4,skills:[],...extra});
function careerState(){const user=player('user-player','Usuario',72,'CM',{isUser:true}),star=player('star','Figura',86,'CAM'),mate=player('mate','Socio',74,'CM'),rival=player('rival','Competidor',70,'CM'),vet=player('vet','Veterano',76,'CDM',{age:31}),kid=player('kid','Juvenil',68,'RW',{age:20,potential:88});return{season:1,week:1,seasonComplete:false,clubId:'club',player:user,world:{club:{roster:[user,star,mate,rival,vet,kid]}},progress:{fans:1000,reputation:12},campaign:{coachTrust:50,lockerRoom:50,media:50,relationships:{},seenEvents:[],currentEvent:null,resolved:[]},lastMatch:null};}

test('one career decision is available per week and cannot be farmed repeatedly',()=>{const state=careerState(),event=getWeeklyInteraction(state);assert.ok(event);const choice=event.choices[0],first=resolveInteraction(state,choice.id);assert.equal(first.ok,true);const resolvedCount=state.campaign.resolved.length,trust=state.campaign.coachTrust,locker=state.campaign.lockerRoom,media=state.campaign.media;assert.equal(getWeeklyInteraction(state),null);assert.equal(weeklyDecisionGate(state).ok,true);const second=resolveInteraction(state,choice.id);assert.equal(second.ok,false);assert.equal(state.campaign.resolved.length,resolvedCount);assert.deepEqual([state.campaign.coachTrust,state.campaign.lockerRoom,state.campaign.media],[trust,locker,media]);});

test('career moments rotate instead of repeating the same deterministic button every week',()=>{const state=careerState(),ids=[];for(let week=1;week<=6;week++){state.week=week;const event=getWeeklyInteraction(state);assert.ok(event);ids.push(event.id);assert.equal(resolveInteraction(state,event.choices[0].id).ok,true);}for(let i=1;i<ids.length;i++)assert.notEqual(ids[i],ids[i-1]);assert.ok(new Set(ids).size>=4,`expected event variety, got ${ids.join(', ')}`);});

test('matchday gate remains closed until the weekly decision is actually resolved',()=>{const state=careerState(),gate=weeklyDecisionGate(state);assert.equal(gate.ok,false);assert.ok(gate.event);assert.match(gate.message,/Resolvé/);assert.equal(resolveInteraction(state,gate.event.choices[0].id).ok,true);assert.equal(weeklyDecisionGate(state).ok,true);});

test('teammate chemistry persists separately from hierarchy and changes pair coordination',()=>{const state=careerState();syncCareerChemistryState(state);const before=relationshipValue(state,'mate'),other=relationshipValue(state,'rival');assert.equal(before,other);adjustRelationship(state,'mate',18,'test');syncCareerChemistryState(state);assert.equal(relationshipValue(state,'mate'),before+18);assert.ok(state.player.chemistryMap.mate>state.player.chemistryMap.rival);const hierarchy=teamHierarchySnapshot(state,6),star=hierarchy.find(x=>x.id==='star'),rival=hierarchy.find(x=>x.id==='rival');assert.ok(star.hierarchy>rival.hierarchy);});

test('equally viable pass lanes are biased toward a high-chemistry high-hierarchy teammate, not tele-guided',()=>{const passer={id:'p',team:0,role:'CM',x:420,y:350,vx:0,vy:0,r:7,data:{passing:76,vision:78,chemistryMap:{star:84,other:34},teamChemistry:55}},star={id:'star',team:0,role:'CAM',x:575,y:300,vx:.3,vy:0,r:7,data:{pace:74,teamHierarchy:.94}},other={id:'other',team:0,role:'CAM',x:575,y:400,vx:.3,vy:0,r:7,data:{pace:74,teamHierarchy:.20}},d1={id:'d1',team:1,role:'CB',x:870,y:250,vx:0,vy:0,r:7,data:{pace:68}},d2={id:'d2',team:1,role:'CB',x:870,y:450,vx:0,vy:0,r:7,data:{pace:68}},gk={id:'gk',team:1,role:'GK',x:1010,y:350,vx:0,vy:0,r:7,data:{pace:60}},engine={players:[passer,star,other,d1,d2,gk],ball:{x:425,y:350}};const options=chemistryAdjustedPassOptions(engine,passer);assert.equal(options[0].player.id,'star');assert.ok(options[0].adjustedScore>options.find(x=>x.player.id==='other').adjustedScore);assert.ok(options.every(x=>Number.isFinite(x.aim.x)&&Number.isFinite(x.aim.y)));});

test('low chemistry delays recognition of a pass intention while high chemistry anticipates it',()=>{const make=(chem)=>{const receiver={id:`r${chem}`,team:0,role:'CM',x:560,y:350,vx:.4,vy:0,data:{pace:72}},passer={id:`p${chem}`,team:0,role:'CM',x:430,y:350,data:{passing:75}},engine={tick:100,armKick(p,aim,power,type,meta){p.kickIntent={aimX:aim.x,aimY:aim.y,power,type,...meta};return true;},flash(){}};const option={player:receiver,kind:'progressive',aim:{x:565,y:350},distance:135,loft:false,chemistry:chem,hierarchy:.6};assert.equal(armChemistryPass(engine,passer,option),true);return receiver.receiveIntent;};const high=make(88),low=make(30);assert.ok(high.readyTick<low.readyTick);assert.equal(high.chemistry,88);assert.equal(low.chemistry,30);});

test('completed physical passes involving the user are recorded as relationship evidence',()=>{const user=player('user-player','Usuario',72,'CM',{isUser:true}),mate=player('mate','Socio',74,'CM'),away1=player('away1','Rival 1',72,'CM'),away2=player('away2','Rival 2',72,'ST'),engine=new MatchEngine([user,mate],[away1,away2],{userId:'user-player',seed:'chem-ledger'}),u=engine.playerById('user-player'),m=engine.playerById('mate');engine.tick=20;engine.ball.passerId=u.id;engine.ball.intendedReceiverId=m.id;engine.ball.lastPlayerId=u.id;engine.ball.lastTeam=0;engine.ball.lastTouchTick=15;engine.registerPhysicalTouch(m,'touch');const perf=engine.userPerformance();assert.equal(perf.chemistryLinks.length,1);assert.equal(perf.chemistryLinks[0].teammateId,'mate');assert.equal(perf.chemistryLinks[0].completed,1);});

test('match chemistry growth is processed once per fixture and cannot be reloaded for infinite gain',()=>{const state=careerState(),before=relationshipValue(state,'mate');state.lastMatch={fixtureId:'fixture-1',score:[2,1],userPerformance:{rating:7.8,chemistryLinks:[{teammateId:'mate',completed:4,given:2,received:2}]}};const first=applyLatestMatchChemistry(state),after=relationshipValue(state,'mate');assert.equal(first.changed,true);assert.ok(after>before);const second=applyLatestMatchChemistry(state);assert.equal(second.changed,false);assert.equal(relationshipValue(state,'mate'),after);});

test('UI source hard-blocks kickoff and exposes chemistry and hierarchy instead of another farm button',()=>{const ui=fs.readFileSync(new URL('../career-rhythm-ui-v1.js',import.meta.url),'utf8');assert.match(ui,/kick\.disabled=true/);assert.match(ui,/stopImmediatePropagation/);assert.match(ui,/QUÍMICA DE EQUIPO/);assert.match(ui,/JERARQUÍA DEPORTIVA/);});
